package com.lcampos.duration_per_tech

import com.lcampos.duration_per_tech.TechCategory._

sealed trait TechCategory {
  val uiRepresentation: String
  val priorityInOrdering: Int // Lower is means first in order
}

object TechCategory {
  case object ProgrammingLanguage extends TechCategory {
    val uiRepresentation: String = "Programming Languages"
    val priorityInOrdering: Int = 1
  }

  case object Framework extends TechCategory {
    val uiRepresentation: String = "Frameworks"
    val priorityInOrdering: Int = 2
  }

  case object Platform extends TechCategory {
    val uiRepresentation: String = "Platforms"
    val priorityInOrdering: Int = 3
  }

  case object Library extends TechCategory {
    val uiRepresentation: String = "Libraries"
    val priorityInOrdering: Int = 4
  }

  case object Mobile extends TechCategory {
    val uiRepresentation: String = "Mobile"
    val priorityInOrdering: Int = 5
  }

  case object Database extends TechCategory {
    val uiRepresentation: String = "Databases"
    val priorityInOrdering: Int = 6
  }

  case object CICD extends TechCategory {
    val uiRepresentation: String = "CI/CD"
    val priorityInOrdering: Int = 7
  }

  case object Cloud extends TechCategory {
    val uiRepresentation: String = "Cloud"
    val priorityInOrdering: Int = 8
  }

  case object InfrastructureTool extends TechCategory {
    val uiRepresentation: String = "Infrastructure Tools"
    val priorityInOrdering: Int = 9
  }

  case object QueryLanguage extends TechCategory {
    val uiRepresentation: String = "Query Languages"
    val priorityInOrdering: Int = 10
  }

  case object TestAndQA extends TechCategory {
    val uiRepresentation: String = "Test and QA"
    val priorityInOrdering: Int = 11
  }

  case object BuildTool extends TechCategory {
    val uiRepresentation: String = "Build Tools"
    val priorityInOrdering: Int = 12
  }

  case object Tool extends TechCategory {
    val uiRepresentation: String = "Tools"
    val priorityInOrdering: Int = 13
  }

  case object OperatingSystem extends TechCategory {
    val uiRepresentation: String = "Operating System"
    val priorityInOrdering: Int = 14
  }

  case object Other extends TechCategory {
    val uiRepresentation: String = "Other"
    val priorityInOrdering: Int = 15
  }

  implicit def techCategoryOrdering: Ordering[TechCategory] = (x: TechCategory, y: TechCategory) =>
    x.priorityInOrdering compare y.priorityInOrdering
}

case class Tech(name: String, aliases: Set[String], category: TechCategory) {
  lazy val aliasesWithDot: Set[String] = aliases.filter(_.contains("."))
  lazy val multiWordAliases: Set[String] = aliases.filter(_.split(" ").length > 1)
}

object Tech {

  /**
   * Sources:
   * - https://github.com/sindresorhus/awesome
   */

  val all: List[Tech] = List(
    // ################# Programming languages #################
    Tech("A#", Set("A#"), ProgrammingLanguage),
    Tech("A+", Set("A+"), ProgrammingLanguage),
    Tech("A++", Set("A++"), ProgrammingLanguage),
    Tech("ABAP", Set("ABAP"), ProgrammingLanguage),
    Tech("ABC ALGOL", Set("ABC ALGOL"), ProgrammingLanguage),
    Tech("ABSET", Set("ABSET"), ProgrammingLanguage),
    Tech("ABSYS", Set("ABSYS"), ProgrammingLanguage),
    Tech("Accent", Set("Accent"), ProgrammingLanguage),
    Tech("ACL2", Set("ACL2"), ProgrammingLanguage),
    Tech("Action!", Set("Action!"), ProgrammingLanguage),
    Tech("ActionScript", Set("ActionScript"), ProgrammingLanguage),
    Tech("Ada", Set("Ada"), ProgrammingLanguage),
    Tech("Adenine", Set("Adenine"), ProgrammingLanguage),
    Tech("Agda", Set("Agda"), ProgrammingLanguage),
    Tech("Agilent VEE", Set("Agilent VEE"), ProgrammingLanguage),
    Tech("AIMMS", Set("AIMMS"), ProgrammingLanguage),
    Tech("Alef", Set("Alef"), ProgrammingLanguage),
    Tech("ALGOL 58", Set("ALGOL 58"), ProgrammingLanguage),
    Tech("ALGOL 60", Set("ALGOL 60"), ProgrammingLanguage),
    Tech("ALGOL 68", Set("ALGOL 68"), ProgrammingLanguage),
    Tech("AmbientTalk", Set("AmbientTalk"), ProgrammingLanguage),
    Tech("AppleScript", Set("AppleScript"), ProgrammingLanguage),
    Tech("Arc", Set("Arc"), ProgrammingLanguage),
    Tech("ARexx", Set("ARexx"), ProgrammingLanguage),
    Tech("Argus", Set("Argus"), ProgrammingLanguage),
    Tech("AspectJ", Set("AspectJ"), ProgrammingLanguage),
    Tech("Assembly language", Set("Assembly Language"), ProgrammingLanguage),
    Tech("Ateji PX", Set("Ateji PX"), ProgrammingLanguage),
    Tech("AutoHotkey", Set("AutoHotkey"), ProgrammingLanguage),
    Tech("Autocoder", Set("Autocoder"), ProgrammingLanguage),
    Tech("AutoIt", Set("AutoIt"), ProgrammingLanguage),
    Tech("Averest", Set("Averest"), ProgrammingLanguage),
    Tech("AWK", Set("AWK"), ProgrammingLanguage),
    Tech("Axum", Set("Axum"), ProgrammingLanguage),
    Tech("Babbage", Set("Babbage"), ProgrammingLanguage),
    Tech("Bash", Set("Bash"), ProgrammingLanguage),
    Tech("BASIC", Set("BASIC"), ProgrammingLanguage),
    Tech("BeanShell", Set("BeanShell"), ProgrammingLanguage),
    Tech("Bertrand", Set("Bertrand"), ProgrammingLanguage),
    Tech("Bigwig", Set("Bigwig"), ProgrammingLanguage),
    Tech("BLISS", Set("BLISS"), ProgrammingLanguage),
    Tech("Bourne shell", Set("Bourne shell"), ProgrammingLanguage),
    Tech("BREW", Set("BREW"), ProgrammingLanguage),
    Tech("BPEL", Set("BPEL"), ProgrammingLanguage),
    Tech("C", Set("C"), ProgrammingLanguage),
    Tech("C--", Set("C--"), ProgrammingLanguage),
    Tech("C++", Set("C++"), ProgrammingLanguage),
    Tech("C#", Set("C#"), ProgrammingLanguage),
    Tech("Caché ObjectScript", Set("Caché ObjectScript"), ProgrammingLanguage),
    Tech("C Shell", Set("C Shell"), ProgrammingLanguage),
    Tech("Caml", Set("Caml"), ProgrammingLanguage),
    Tech("Cayenne", Set("Cayenne"), ProgrammingLanguage),
    Tech("CDuce", Set("CDuce"), ProgrammingLanguage),
    Tech("Cecil", Set("Cecil"), ProgrammingLanguage),
    Tech("Cesil", Set("Cesil"), ProgrammingLanguage),
    Tech("Ceylon", Set("Ceylon"), ProgrammingLanguage),
    Tech("CFEngine", Set("CFEngine"), ProgrammingLanguage),
    Tech("CFML", Set("CFML"), ProgrammingLanguage),
    Tech("Chapel", Set("Chapel"), ProgrammingLanguage),
    Tech("CHIP-8", Set("CHIP-8"), ProgrammingLanguage),
    Tech("chomski", Set("chomski"), ProgrammingLanguage),
    Tech("Clarion", Set("Clarion"), ProgrammingLanguage),
    Tech("Clipper", Set("Clipper"), ProgrammingLanguage),
    Tech("CLIST", Set("CLIST"), ProgrammingLanguage),
    Tech("Clojure", Set("Clojure"), ProgrammingLanguage),
    Tech("COBOL", Set("COBOL"), ProgrammingLanguage),
    Tech("CoffeeScript", Set("CoffeeScript"), ProgrammingLanguage),
    Tech("ColdC", Set("ColdC"), ProgrammingLanguage),
    Tech("ColdFusion", Set("ColdFusion"), ProgrammingLanguage),
    Tech("COMAL", Set("COMAL"), ProgrammingLanguage),
    Tech("COMIT", Set("COMIT"), ProgrammingLanguage),
    Tech("Common Lisp", Set("Common Lisp"), ProgrammingLanguage),
    Tech("COMPASS", Set("COMPASS"), ProgrammingLanguage),
    Tech("Component Pascal", Set("Component Pascal"), ProgrammingLanguage),
    Tech("Converge", Set("Converge"), ProgrammingLanguage),
    Tech("Coq", Set("Coq"), ProgrammingLanguage),
    Tech("Coral 66", Set("Coral 66"), ProgrammingLanguage),
    Tech("CorVision", Set("CorVision"), ProgrammingLanguage),
    Tech("COWSEL", Set("COWSEL"), ProgrammingLanguage),
    Tech("Csound", Set("Csound"), ProgrammingLanguage),
    Tech("CUDA", Set("CUDA"), ProgrammingLanguage),
    Tech("Curl", Set("Curl"), ProgrammingLanguage),
    Tech("Curry", Set("Curry"), ProgrammingLanguage),
    Tech("Cyclone", Set("Cyclone"), ProgrammingLanguage),
    Tech("Cython", Set("Cython"), ProgrammingLanguage),
    Tech("DASL", Set("DASL"), ProgrammingLanguage),
    Tech("Dart", Set("Dart"), ProgrammingLanguage),
    Tech("DataFlex", Set("DataFlex"), ProgrammingLanguage),
    Tech("Datalog", Set("Datalog"), ProgrammingLanguage),
    Tech("DATATRIEVE", Set("DATATRIEVE"), ProgrammingLanguage),
    Tech("dBase", Set("dBase"), ProgrammingLanguage),
    Tech("Deesel", Set("Deesel"), ProgrammingLanguage),
    Tech("Delphi", Set("Delphi"), ProgrammingLanguage),
    Tech("DinkC", Set("DinkC"), ProgrammingLanguage),
    Tech("DIBOL", Set("DIBOL"), ProgrammingLanguage),
    Tech("Draco", Set("Draco"), ProgrammingLanguage),
    Tech("DRAKON", Set("DRAKON"), ProgrammingLanguage),
    Tech("Dylan", Set("Dylan"), ProgrammingLanguage),
    Tech("DYNAMO", Set("DYNAMO"), ProgrammingLanguage),
    Tech("E#", Set("E#"), ProgrammingLanguage),
    Tech("ECMAScript", Set("ECMAScript"), ProgrammingLanguage),
    Tech("EGL", Set("EGL"), ProgrammingLanguage),
    Tech("Eiffel", Set("Eiffel"), ProgrammingLanguage),
    Tech("ELAN", Set("ELAN"), ProgrammingLanguage),
    Tech("Elixir", Set("Elixir"), ProgrammingLanguage),
    Tech("Elm", Set("Elm"), ProgrammingLanguage),
    Tech("Emacs Lisp", Set("Emacs Lisp"), ProgrammingLanguage),
    Tech("Emerald", Set("Emerald"), ProgrammingLanguage),
    Tech("Epigram", Set("Epigram"), ProgrammingLanguage),
    Tech("Erlang", Set("Erlang"), ProgrammingLanguage),
    Tech("Escapade", Set("Escapade"), ProgrammingLanguage),
    Tech("Escher", Set("Escher"), ProgrammingLanguage),
    Tech("ESPOL", Set("ESPOL"), ProgrammingLanguage),
    Tech("Esterel", Set("Esterel"), ProgrammingLanguage),
    Tech("Etoys", Set("Etoys"), ProgrammingLanguage),
    Tech("Euclid", Set("Euclid"), ProgrammingLanguage),
    Tech("Euler", Set("Euler"), ProgrammingLanguage),
    Tech("Euphoria", Set("Euphoria"), ProgrammingLanguage),
    Tech("EusLisp", Set("EusLisp"), ProgrammingLanguage),
    Tech("CMS EXEC", Set("CMS EXEC"), ProgrammingLanguage),
    Tech("EXEC 2", Set("EXEC 2"), ProgrammingLanguage),
    Tech("Executable UML", Set("Executable UML"), ProgrammingLanguage),
    Tech("F#", Set("F#"), ProgrammingLanguage),
    Tech("Fantom", Set("Fantom"), ProgrammingLanguage),
    Tech("FAUST", Set("FAUST"), ProgrammingLanguage),
    Tech("Ferite", Set("Ferite"), ProgrammingLanguage),
    Tech("Fjölnir", Set("Fjölnir"), ProgrammingLanguage),
    Tech("Flavors", Set("Flavors"), ProgrammingLanguage),
    Tech("Flex", Set("Flex"), ProgrammingLanguage),
    Tech("FORMAC", Set("FORMAC"), ProgrammingLanguage),
    Tech("@Formula", Set("@Formula"), ProgrammingLanguage),
    Tech("Forth", Set("Forth"), ProgrammingLanguage),
    Tech("Fortran", Set("Fortran"), ProgrammingLanguage),
    Tech("Fortress", Set("Fortress"), ProgrammingLanguage),
    Tech("FoxBase", Set("FoxBase"), ProgrammingLanguage),
    Tech("FoxPro", Set("FoxPro"), ProgrammingLanguage),
    Tech("FPr", Set("FPr"), ProgrammingLanguage),
    Tech("Franz Lisp", Set("Franz Lisp"), ProgrammingLanguage),
    Tech("Frege", Set("Frege"), ProgrammingLanguage),
    Tech("F-Script", Set("F-Script"), ProgrammingLanguage),
    Tech("FSProg", Set("FSProg"), ProgrammingLanguage),
    Tech("Google Apps Script", Set("Google Apps Script"), ProgrammingLanguage),
    Tech("Game Maker Language", Set("Game Maker Language"), ProgrammingLanguage),
    Tech("GameMonkey Script", Set("GameMonkey Script"), ProgrammingLanguage),
    Tech("GAMS", Set("GAMS"), ProgrammingLanguage),
    Tech("G-code", Set("G-code"), ProgrammingLanguage),
    Tech("Genie", Set("Genie"), ProgrammingLanguage),
    Tech("GDL", Set("GDL"), ProgrammingLanguage),
    Tech("Gibiane", Set("Gibiane"), ProgrammingLanguage),
    Tech("GEORGE", Set("GEORGE"), ProgrammingLanguage),
    Tech("GLSL", Set("GLSL"), ProgrammingLanguage),
    Tech("GNU E", Set("GNU E"), ProgrammingLanguage),
    Tech("Golang", Set("Golang", "golang", "Go"), ProgrammingLanguage),
    Tech("Gödel", Set("Gödel"), ProgrammingLanguage),
    Tech("Godiva", Set("Godiva"), ProgrammingLanguage),
    Tech("Goo", Set("Goo"), ProgrammingLanguage),
    Tech("Gosu", Set("Gosu"), ProgrammingLanguage),
    Tech("GOTRAN", Set("GOTRAN"), ProgrammingLanguage),
    Tech("GPSS", Set("GPSS"), ProgrammingLanguage),
    Tech("GraphTalk", Set("GraphTalk"), ProgrammingLanguage),
    Tech("GRASS", Set("GRASS"), ProgrammingLanguage),
    Tech("Groovy", Set("Groovy"), ProgrammingLanguage),
    Tech("Hack", Set("Hack"), ProgrammingLanguage),
    Tech("Harbour", Set("Harbour"), ProgrammingLanguage),
    Tech("Hartmann pipelines", Set("Hartmann pipelines"), ProgrammingLanguage),
    Tech("Haskell", Set("Haskell"), ProgrammingLanguage),
    Tech("Haxe", Set("Haxe"), ProgrammingLanguage),
    Tech("High Level Assembly", Set("High Level Assembly"), ProgrammingLanguage),
    Tech("HLSL", Set("HLSL"), ProgrammingLanguage),
    Tech("Hope", Set("Hope"), ProgrammingLanguage),
    Tech("Hugo", Set("Hugo"), ProgrammingLanguage),
    Tech("Hume", Set("Hume"), ProgrammingLanguage),
    Tech("HyperTalk", Set("HyperTalk"), ProgrammingLanguage),
    Tech("ICI", Set("ICI"), ProgrammingLanguage),
    Tech("Icon", Set("Icon"), ProgrammingLanguage),
    Tech("IDL", Set("IDL"), ProgrammingLanguage),
    Tech("Idris", Set("Idris"), ProgrammingLanguage),
    Tech("IMP", Set("IMP"), ProgrammingLanguage),
    Tech("Inform", Set("Inform"), ProgrammingLanguage),
    Tech("Ioke", Set("Ioke"), ProgrammingLanguage),
    Tech("IPL", Set("IPL"), ProgrammingLanguage),
    Tech("IPTSCRAE", Set("IPTSCRAE"), ProgrammingLanguage),
    Tech("ISLISP", Set("ISLISP"), ProgrammingLanguage),
    Tech("ISPF", Set("ISPF"), ProgrammingLanguage),
    Tech("ISWIM", Set("ISWIM"), ProgrammingLanguage),
    Tech("J#", Set("J#"), ProgrammingLanguage),
    Tech("J++", Set("J++"), ProgrammingLanguage),
    Tech("JADE", Set("JADE"), ProgrammingLanguage),
    Tech("Jako", Set("Jako"), ProgrammingLanguage),
    Tech("JAL", Set("JAL"), ProgrammingLanguage),
    Tech("Janus", Set("Janus"), ProgrammingLanguage),
    Tech("JASS", Set("JASS"), ProgrammingLanguage),
    Tech("Java", Set("JAVA", "Java", "Java8", "Java11", "JavaEE"), ProgrammingLanguage),
    Tech("JavaScript", Set("JavaScript", "Javascript"), ProgrammingLanguage),
    Tech("JCL", Set("JCL"), ProgrammingLanguage),
    Tech("Join Java", Set("Join Java"), ProgrammingLanguage),
    Tech("JOSS", Set("JOSS"), ProgrammingLanguage),
    Tech("Joule", Set("Joule"), ProgrammingLanguage),
    Tech("JOVIAL", Set("JOVIAL"), ProgrammingLanguage),
    Tech("JScript", Set("JScript"), ProgrammingLanguage),
    Tech("JavaFX Script", Set("JavaFX Script"), ProgrammingLanguage),
    Tech("Julia", Set("Julia"), ProgrammingLanguage),
    Tech("Jython", Set("Jython"), ProgrammingLanguage),
    Tech("Kaleidoscope", Set("Kaleidoscope"), ProgrammingLanguage),
    Tech("Karel", Set("Karel"), ProgrammingLanguage),
    Tech("Karel++", Set("Karel++"), ProgrammingLanguage),
    Tech("KEE", Set("KEE"), ProgrammingLanguage),
    Tech("Kixtart", Set("Kixtart"), ProgrammingLanguage),
    Tech("KIF", Set("KIF"), ProgrammingLanguage),
    Tech("Kojo", Set("Kojo"), ProgrammingLanguage),
    Tech("Kotlin", Set("Kotlin"), ProgrammingLanguage),
    Tech("KRC", Set("KRC"), ProgrammingLanguage),
    Tech("KRL", Set("KRL"), ProgrammingLanguage),
    Tech("KUKA", Set("KUKA"), ProgrammingLanguage),
    Tech("KRYPTON", Set("KRYPTON"), ProgrammingLanguage),
    Tech("ksh", Set("ksh"), ProgrammingLanguage),
    Tech("LabVIEW", Set("LabVIEW"), ProgrammingLanguage),
    Tech("Ladder", Set("Ladder"), ProgrammingLanguage),
    Tech("Lagoona", Set("Lagoona"), ProgrammingLanguage),
    Tech("LANSA", Set("LANSA"), ProgrammingLanguage),
    Tech("Lasso", Set("Lasso"), ProgrammingLanguage),
    Tech("LaTeX", Set("LaTeX"), ProgrammingLanguage),
    Tech("Lava", Set("Lava"), ProgrammingLanguage),
    Tech("Leda", Set("Leda"), ProgrammingLanguage),
    Tech("Legoscript", Set("Legoscript"), ProgrammingLanguage),
    Tech("LIL", Set("LIL"), ProgrammingLanguage),
    Tech("LilyPond", Set("LilyPond"), ProgrammingLanguage),
    Tech("Limbo", Set("Limbo"), ProgrammingLanguage),
    Tech("Limnor", Set("Limnor"), ProgrammingLanguage),
    Tech("LINC", Set("LINC"), ProgrammingLanguage),
    Tech("Lingo", Set("Lingo"), ProgrammingLanguage),
    Tech("Linoleum", Set("Linoleum"), ProgrammingLanguage),
    Tech("LIS", Set("LIS"), ProgrammingLanguage),
    Tech("LISA", Set("LISA"), ProgrammingLanguage),
    Tech("Lisaac", Set("Lisaac"), ProgrammingLanguage),
    Tech("Lisp", Set("Lisp"), ProgrammingLanguage),
    Tech("Lite-C", Set("Lite-C"), ProgrammingLanguage),
    Tech("Lithe", Set("Lithe"), ProgrammingLanguage),
    Tech("Little b", Set("Little b"), ProgrammingLanguage),
    Tech("Logo", Set("Logo"), ProgrammingLanguage),
    Tech("Logtalk", Set("Logtalk"), ProgrammingLanguage),
    Tech("LPC", Set("LPC"), ProgrammingLanguage),
    Tech("LSE", Set("LSE"), ProgrammingLanguage),
    Tech("LSL", Set("LSL"), ProgrammingLanguage),
    Tech("LiveCode", Set("LiveCode"), ProgrammingLanguage),
    Tech("LiveScript", Set("LiveScript"), ProgrammingLanguage),
    Tech("Lua", Set("Lua"), ProgrammingLanguage),
    Tech("Lucid", Set("Lucid"), ProgrammingLanguage),
    Tech("Lustre", Set("Lustre"), ProgrammingLanguage),
    Tech("LYaPAS", Set("LYaPAS"), ProgrammingLanguage),
    Tech("Lynx", Set("Lynx"), ProgrammingLanguage),
    Tech("M2001", Set("M2001"), ProgrammingLanguage),
    Tech("M4", Set("M4"), ProgrammingLanguage),
    Tech("MAD/I", Set("MAD/I"), ProgrammingLanguage),
    Tech("Magik", Set("Magik"), ProgrammingLanguage),
    Tech("Magma", Set("Magma"), ProgrammingLanguage),
    Tech("Maple", Set("Maple"), ProgrammingLanguage),
    Tech("MAPPER", Set("MAPPER"), ProgrammingLanguage),
    Tech("Mary", Set("Mary"), ProgrammingLanguage),
    Tech("Mathematica", Set("Mathematica"), ProgrammingLanguage),
    Tech("MATLAB", Set("MATLAB"), ProgrammingLanguage),
    Tech("Maxima", Set("Maxima"), ProgrammingLanguage),
    Tech("Macsyma", Set("Macsyma"), ProgrammingLanguage),
    Tech("MaxScript", Set("MaxScript"), ProgrammingLanguage),
    Tech("MDL", Set("MDL"), ProgrammingLanguage),
    Tech("Mercury", Set("Mercury"), ProgrammingLanguage),
    Tech("Mesa", Set("Mesa"), ProgrammingLanguage),
    Tech("Metacard", Set("Metacard"), ProgrammingLanguage),
    Tech("Metafont", Set("Metafont"), ProgrammingLanguage),
    Tech("MetaL", Set("MetaL"), ProgrammingLanguage),
    Tech("Microcode", Set("Microcode"), ProgrammingLanguage),
    Tech("MicroScript", Set("MicroScript"), ProgrammingLanguage),
    Tech("MIIS", Set("MIIS"), ProgrammingLanguage),
    Tech("MillScript", Set("MillScript"), ProgrammingLanguage),
    Tech("MIMIC", Set("MIMIC"), ProgrammingLanguage),
    Tech("Mirah", Set("Mirah"), ProgrammingLanguage),
    Tech("Miranda", Set("Miranda"), ProgrammingLanguage),
    Tech("ML", Set("ML"), ProgrammingLanguage),
    Tech("Moby", Set("Moby"), ProgrammingLanguage),
    Tech("Modelica", Set("Modelica"), ProgrammingLanguage),
    Tech("Mohol", Set("Mohol"), ProgrammingLanguage),
    Tech("MOO", Set("MOO"), ProgrammingLanguage),
    Tech("Mortran", Set("Mortran"), ProgrammingLanguage),
    Tech("Mouse", Set("Mouse"), ProgrammingLanguage),
    Tech("MPD", Set("MPD"), ProgrammingLanguage),
    Tech("CIL", Set("CIL"), ProgrammingLanguage),
    Tech("MSL", Set("MSL"), ProgrammingLanguage),
    Tech("MUMPS", Set("MUMPS"), ProgrammingLanguage),
    Tech("NASM", Set("NASM"), ProgrammingLanguage),
    Tech("NATURAL", Set("NATURAL"), ProgrammingLanguage),
    Tech("Napier88", Set("Napier88"), ProgrammingLanguage),
    Tech("Neko", Set("Neko"), ProgrammingLanguage),
    Tech("Nemerle", Set("Nemerle"), ProgrammingLanguage),
    Tech("nesC", Set("nesC"), ProgrammingLanguage),
    Tech("NESL", Set("NESL"), ProgrammingLanguage),
    Tech("Net.Data", Set("Net.Data"), ProgrammingLanguage),
    Tech("NetLogo", Set("NetLogo"), ProgrammingLanguage),
    Tech("NetRexx", Set("NetRexx"), ProgrammingLanguage),
    Tech("NewLISP", Set("NewLISP"), ProgrammingLanguage),
    Tech("NEWP", Set("NEWP"), ProgrammingLanguage),
    Tech("Newspeak", Set("Newspeak"), ProgrammingLanguage),
    Tech("NewtonScript", Set("NewtonScript"), ProgrammingLanguage),
    Tech("NGL", Set("NGL"), ProgrammingLanguage),
    Tech("Nial", Set("Nial"), ProgrammingLanguage),
    Tech("Nickle", Set("Nickle"), ProgrammingLanguage),
    Tech("Nim", Set("Nim"), ProgrammingLanguage),
    Tech("NPL", Set("NPL"), ProgrammingLanguage),
    Tech("Not eXactly C", Set("Not eXactly C"), ProgrammingLanguage),
    Tech("Not Quite C", Set("Not Quite C"), ProgrammingLanguage),
    Tech("NSIS", Set("NSIS"), ProgrammingLanguage),
    Tech("Nu", Set("Nu"), ProgrammingLanguage),
    Tech("NWScript", Set("NWScript"), ProgrammingLanguage),
    Tech("Oak", Set("Oak"), ProgrammingLanguage),
    Tech("Oberon", Set("Oberon"), ProgrammingLanguage),
    Tech("Obix", Set("Obix"), ProgrammingLanguage),
    Tech("OBJ2", Set("OBJ2"), ProgrammingLanguage),
    Tech("Object Lisp", Set("Object Lisp"), ProgrammingLanguage),
    Tech("ObjectLOGO", Set("ObjectLOGO"), ProgrammingLanguage),
    Tech("Object REXX", Set("Object REXX"), ProgrammingLanguage),
    Tech("Object Pascal", Set("Object Pascal"), ProgrammingLanguage),
    Tech("Objective-C", Set("Objective-C"), ProgrammingLanguage),
    Tech("Objective-J", Set("Objective-J"), ProgrammingLanguage),
    Tech("Obliq", Set("Obliq"), ProgrammingLanguage),
    Tech("Obol", Set("Obol"), ProgrammingLanguage),
    Tech("OCaml", Set("OCaml"), ProgrammingLanguage),
    Tech("occam", Set("occam"), ProgrammingLanguage),
    Tech("occam-π", Set("occam-π"), ProgrammingLanguage),
    Tech("Octave", Set("Octave"), ProgrammingLanguage),
    Tech("OmniMark", Set("OmniMark"), ProgrammingLanguage),
    Tech("Onyx", Set("Onyx"), ProgrammingLanguage),
    Tech("Opa", Set("Opa"), ProgrammingLanguage),
    Tech("Opal", Set("Opal"), ProgrammingLanguage),
    Tech("OpenCL", Set("OpenCL"), ProgrammingLanguage),
    Tech("OpenEdge ABL", Set("OpenEdge ABL"), ProgrammingLanguage),
    Tech("OPL", Set("OPL"), ProgrammingLanguage),
    Tech("OPS5", Set("OPS5"), ProgrammingLanguage),
    Tech("OptimJ", Set("OptimJ"), ProgrammingLanguage),
    Tech("Orc", Set("Orc"), ProgrammingLanguage),
    Tech("Oriel", Set("Oriel"), ProgrammingLanguage),
    Tech("Orwell", Set("Orwell"), ProgrammingLanguage),
    Tech("Oxygene", Set("Oxygene"), ProgrammingLanguage),
    Tech("Oz", Set("Oz"), ProgrammingLanguage),
    Tech("P#", Set("P#"), ProgrammingLanguage),
    Tech("ParaSail", Set("ParaSail"), ProgrammingLanguage),
    Tech("Pascal", Set("Pascal"), ProgrammingLanguage),
    Tech("Pawn", Set("Pawn"), ProgrammingLanguage),
    Tech("PCASTL", Set("PCASTL"), ProgrammingLanguage),
    Tech("PCF", Set("PCF"), ProgrammingLanguage),
    Tech("PEARL", Set("PEARL"), ProgrammingLanguage),
    Tech("PeopleCode", Set("PeopleCode"), ProgrammingLanguage),
    Tech("Perl", Set("Perl"), ProgrammingLanguage),
    Tech("PDL", Set("PDL"), ProgrammingLanguage),
    Tech("PHP", Set("PHP"), ProgrammingLanguage),
    Tech("Phrogram", Set("Phrogram"), ProgrammingLanguage),
    Tech("Pico", Set("Pico"), ProgrammingLanguage),
    Tech("Picolisp", Set("Picolisp"), ProgrammingLanguage),
    Tech("Pict", Set("Pict"), ProgrammingLanguage),
    Tech("Pike", Set("Pike"), ProgrammingLanguage),
    Tech("PIKT", Set("PIKT"), ProgrammingLanguage),
    Tech("PILOT", Set("PILOT"), ProgrammingLanguage),
    Tech("Pipelines", Set("Pipelines"), ProgrammingLanguage),
    Tech("Pizza", Set("Pizza"), ProgrammingLanguage),
    Tech("PL-11", Set("PL-11"), ProgrammingLanguage),
    Tech("PL/0", Set("PL/0"), ProgrammingLanguage),
    Tech("PL/B", Set("PL/B"), ProgrammingLanguage),
    Tech("PL/C", Set("PL/C"), ProgrammingLanguage),
    Tech("PL/I", Set("PL/I"), ProgrammingLanguage),
    Tech("PL/M", Set("PL/M"), ProgrammingLanguage),
    Tech("PL/P", Set("PL/P"), ProgrammingLanguage),
    Tech("PL/SQL", Set("PL/SQL"), ProgrammingLanguage),
    Tech("PL360", Set("PL360"), ProgrammingLanguage),
    Tech("PLANC", Set("PLANC"), ProgrammingLanguage),
    Tech("Plankalkül", Set("Plankalkül"), ProgrammingLanguage),
    Tech("Planner", Set("Planner"), ProgrammingLanguage),
    Tech("PLEX", Set("PLEX"), ProgrammingLanguage),
    Tech("PLEXIL", Set("PLEXIL"), ProgrammingLanguage),
    Tech("Plus", Set("Plus"), ProgrammingLanguage),
    Tech("POP-11", Set("POP-11"), ProgrammingLanguage),
    Tech("PostScript", Set("PostScript"), ProgrammingLanguage),
    Tech("PortablE", Set("PortablE"), ProgrammingLanguage),
    Tech("Powerhouse", Set("Powerhouse"), ProgrammingLanguage),
    Tech("PowerBuilder", Set("PowerBuilder"), ProgrammingLanguage),
    Tech("PowerShell", Set("PowerShell"), ProgrammingLanguage),
    Tech("PPL", Set("PPL"), ProgrammingLanguage),
    Tech("Processing.js", Set("Processing.js"), ProgrammingLanguage),
    Tech("Prograph", Set("Prograph"), ProgrammingLanguage),
    Tech("PROIV", Set("PROIV"), ProgrammingLanguage),
    Tech("Prolog", Set("Prolog"), ProgrammingLanguage),
    Tech("PROMAL", Set("PROMAL"), ProgrammingLanguage),
    Tech("Promela", Set("Promela"), ProgrammingLanguage),
    Tech("PROSE modeling language", Set("PROSE modeling language"), ProgrammingLanguage),
    Tech("PROTEL", Set("PROTEL"), ProgrammingLanguage),
    Tech("ProvideX", Set("ProvideX"), ProgrammingLanguage),
    Tech("Pro*C", Set("Pro*C"), ProgrammingLanguage),
    Tech("Python", Set("Python"), ProgrammingLanguage),
    Tech("Qalb", Set("Qalb"), ProgrammingLanguage),
    Tech("QtScript", Set("QtScript"), ProgrammingLanguage),
    Tech("QuakeC", Set("QuakeC"), ProgrammingLanguage),
    Tech("QPL", Set("QPL"), ProgrammingLanguage),
    Tech("R++", Set("R++"), ProgrammingLanguage),
    Tech("Racket", Set("Racket"), ProgrammingLanguage),
    Tech("RAPID", Set("RAPID"), ProgrammingLanguage),
    Tech("Rapira", Set("Rapira"), ProgrammingLanguage),
    Tech("Ratfiv", Set("Ratfiv"), ProgrammingLanguage),
    Tech("Ratfor", Set("Ratfor"), ProgrammingLanguage),
    Tech("REBOL", Set("REBOL"), ProgrammingLanguage),
    Tech("Redcode", Set("Redcode"), ProgrammingLanguage),
    Tech("REFAL", Set("REFAL"), ProgrammingLanguage),
    Tech("Reia", Set("Reia"), ProgrammingLanguage),
    Tech("Revolution", Set("Revolution"), ProgrammingLanguage),
    Tech("rex", Set("rex"), ProgrammingLanguage),
    Tech("REXX", Set("REXX"), ProgrammingLanguage),
    Tech("Rlab", Set("Rlab"), ProgrammingLanguage),
    Tech("RobotC", Set("RobotC"), ProgrammingLanguage),
    Tech("ROOP", Set("ROOP"), ProgrammingLanguage),
    Tech("RPG", Set("RPG"), ProgrammingLanguage),
    Tech("RPL", Set("RPL"), ProgrammingLanguage),
    Tech("RSL", Set("RSL"), ProgrammingLanguage),
    Tech("Ruby", Set("Ruby"), ProgrammingLanguage),
    Tech("RuneScript", Set("RuneScript"), ProgrammingLanguage),
    Tech("Rust", Set("Rust"), ProgrammingLanguage),
    Tech("SabreTalk", Set("SabreTalk"), ProgrammingLanguage),
    Tech("SAIL", Set("SAIL"), ProgrammingLanguage),
    Tech("SALSA", Set("SALSA"), ProgrammingLanguage),
    Tech("SAM76", Set("SAM76"), ProgrammingLanguage),
    Tech("SAS", Set("SAS"), ProgrammingLanguage),
    Tech("SASL", Set("SASL"), ProgrammingLanguage),
    Tech("Sather", Set("Sather"), ProgrammingLanguage),
    Tech("Sawzall", Set("Sawzall"), ProgrammingLanguage),
    Tech("SBL", Set("SBL"), ProgrammingLanguage),
    Tech("Scala", Set("Scala"), ProgrammingLanguage),
    Tech("Scheme", Set("Scheme"), ProgrammingLanguage),
    Tech("Scilab", Set("Scilab"), ProgrammingLanguage),
    Tech("Script.NET", Set("Script.NET"), ProgrammingLanguage),
    Tech("Sed", Set("Sed"), ProgrammingLanguage),
    Tech("Seed7", Set("Seed7"), ProgrammingLanguage),
    Tech("Self", Set("Self"), ProgrammingLanguage),
    Tech("SenseTalk", Set("SenseTalk"), ProgrammingLanguage),
    Tech("SequenceL", Set("SequenceL"), ProgrammingLanguage),
    Tech("SETL", Set("SETL"), ProgrammingLanguage),
    Tech("Shift Script", Set("Shift Script"), ProgrammingLanguage),
    Tech("SIMPOL", Set("SIMPOL"), ProgrammingLanguage),
    Tech("SIGNAL", Set("SIGNAL"), ProgrammingLanguage),
    Tech("SIMSCRIPT", Set("SIMSCRIPT"), ProgrammingLanguage),
    Tech("Simula", Set("Simula"), ProgrammingLanguage),
    Tech("Simulink", Set("Simulink"), ProgrammingLanguage),
    Tech("SISAL", Set("SISAL"), ProgrammingLanguage),
    Tech("SLIP", Set("SLIP"), ProgrammingLanguage),
    Tech("Smalltalk", Set("Smalltalk"), ProgrammingLanguage),
    Tech("Small Basic", Set("Small Basic"), ProgrammingLanguage),
    Tech("SML", Set("SML"), ProgrammingLanguage),
    Tech("Snap!", Set("Snap!"), ProgrammingLanguage),
    Tech("SNOBOL", Set("SNOBOL"), ProgrammingLanguage),
    Tech("SPITBOL", Set("SPITBOL"), ProgrammingLanguage),
    Tech("Snowball", Set("Snowball"), ProgrammingLanguage),
    Tech("SOL", Set("SOL"), ProgrammingLanguage),
    Tech("Span", Set("Span"), ProgrammingLanguage),
    Tech("SPARK", Set("SPARK"), ProgrammingLanguage),
    Tech("Speedcode", Set("Speedcode"), ProgrammingLanguage),
    Tech("SPIN", Set("SPIN"), ProgrammingLanguage),
    Tech("SPS", Set("SPS"), ProgrammingLanguage),
    Tech("Squeak", Set("Squeak"), ProgrammingLanguage),
    Tech("Squirrel", Set("Squirrel"), ProgrammingLanguage),
    Tech("SR", Set("SR"), ProgrammingLanguage),
    Tech("Starlogo", Set("Starlogo"), ProgrammingLanguage),
    Tech("Strand", Set("Strand"), ProgrammingLanguage),
    Tech("Stata", Set("Stata"), ProgrammingLanguage),
    Tech("Stateflow", Set("Stateflow"), ProgrammingLanguage),
    Tech("Subtext", Set("Subtext"), ProgrammingLanguage),
    Tech("SuperCollider", Set("SuperCollider"), ProgrammingLanguage),
    Tech("SuperTalk", Set("SuperTalk"), ProgrammingLanguage),
    Tech("Swift", Set("Swift"), ProgrammingLanguage),
    Tech("SYMPL", Set("SYMPL"), ProgrammingLanguage),
    Tech("SyncCharts", Set("SyncCharts"), ProgrammingLanguage),
    Tech("SystemVerilog", Set("SystemVerilog"), ProgrammingLanguage),
    Tech("TACL", Set("TACL"), ProgrammingLanguage),
    Tech("TACPOL", Set("TACPOL"), ProgrammingLanguage),
    Tech("TADS", Set("TADS"), ProgrammingLanguage),
    Tech("TAL", Set("TAL"), ProgrammingLanguage),
    Tech("Tcl", Set("Tcl"), ProgrammingLanguage),
    Tech("Tea", Set("Tea"), ProgrammingLanguage),
    Tech("TECO", Set("TECO"), ProgrammingLanguage),
    Tech("TELCOMP", Set("TELCOMP"), ProgrammingLanguage),
    Tech("TeX", Set("TeX"), ProgrammingLanguage),
    Tech("TEX", Set("TEX"), ProgrammingLanguage),
    Tech("TIE", Set("TIE"), ProgrammingLanguage),
    Tech("Timber", Set("Timber"), ProgrammingLanguage),
    Tech("TMG", Set("TMG"), ProgrammingLanguage),
    Tech("Tom", Set("Tom"), ProgrammingLanguage),
    Tech("TOM", Set("TOM"), ProgrammingLanguage),
    Tech("Topspeed", Set("Topspeed"), ProgrammingLanguage),
    Tech("TPU", Set("TPU"), ProgrammingLanguage),
    Tech("Trac", Set("Trac"), ProgrammingLanguage),
    Tech("TTM", Set("TTM"), ProgrammingLanguage),
    Tech("T-SQL", Set("T-SQL"), ProgrammingLanguage),
    Tech("TTCN", Set("TTCN"), ProgrammingLanguage),
    Tech("Turing", Set("Turing"), ProgrammingLanguage),
    Tech("TUTOR", Set("TUTOR"), ProgrammingLanguage),
    Tech("TXL", Set("TXL"), ProgrammingLanguage),
    Tech("TypeScript", Set("TypeScript"), ProgrammingLanguage),
    Tech("Ubercode", Set("Ubercode"), ProgrammingLanguage),
    Tech("Umple", Set("Umple"), ProgrammingLanguage),
    Tech("Unicon", Set("Unicon"), ProgrammingLanguage),
    Tech("Uniface", Set("Uniface"), ProgrammingLanguage),
    Tech("UNITY", Set("UNITY"), ProgrammingLanguage),
    Tech("UnrealScript", Set("UnrealScript"), ProgrammingLanguage),
    Tech("Vala", Set("Vala"), ProgrammingLanguage),
    Tech("VBA", Set("VBA"), ProgrammingLanguage),
    Tech("VBScript", Set("VBScript"), ProgrammingLanguage),
    Tech("Verilog", Set("Verilog"), ProgrammingLanguage),
    Tech("VHDL", Set("VHDL"), ProgrammingLanguage),
    Tech("Visual Basic", Set("Visual Basic"), ProgrammingLanguage),
    Tech("Visual Basic .NET", Set("Visual Basic .NET", "VB.net", "VB.NET"), ProgrammingLanguage),
    Tech("Visual DataFlex", Set("Visual Dataflex"), ProgrammingLanguage),
    Tech("Visual DialogScript", Set("Visual DialogScript"), ProgrammingLanguage),
    Tech("Visual Fortran", Set("Visual Fortran"), ProgrammingLanguage),
    Tech("Visual FoxPro", Set("Visual FoxPro"), ProgrammingLanguage),
    Tech("Visual J++", Set("Visual J++"), ProgrammingLanguage),
    Tech("Visual J#", Set("Visual J#"), ProgrammingLanguage),
    Tech("Visual Objects", Set("Visual Objects"), ProgrammingLanguage),
    Tech("Visual Prolog", Set("Visual Prolog"), ProgrammingLanguage),
    Tech("VSXu", Set("VSXu"), ProgrammingLanguage),
    Tech("Vvvv", Set("Vvvv"), ProgrammingLanguage),
    Tech("WATFIV", Set("WATFIV"), ProgrammingLanguage),
    Tech("WATFOR", Set("WATFOR"), ProgrammingLanguage),
    Tech("WebDNA", Set("WebDNA"), ProgrammingLanguage),
    Tech("WebQL", Set("WebQL"), ProgrammingLanguage),
    Tech("Winbatch", Set("Winbatch"), ProgrammingLanguage),
    Tech("Wolfram", Set("Wolfram"), ProgrammingLanguage),
    Tech("Wyvern", Set("Wyvern"), ProgrammingLanguage),
    Tech("X++", Set("X++"), ProgrammingLanguage),
    Tech("X#", Set("X#"), ProgrammingLanguage),
    Tech("X10", Set("X10"), ProgrammingLanguage),
    Tech("XBL", Set("XBL"), ProgrammingLanguage),
    Tech("XC", Set("XC"), ProgrammingLanguage),
    Tech("XMOS architecture", Set("XMOS architecture"), ProgrammingLanguage),
    Tech("xHarbour", Set("xHarbour"), ProgrammingLanguage),
    Tech("Xojo", Set("Xojo"), ProgrammingLanguage),
    Tech("XOTcl", Set("XOTcl"), ProgrammingLanguage),
    Tech("XPL", Set("XPL"), ProgrammingLanguage),
    Tech("XPL0", Set("XPL0"), ProgrammingLanguage),
    Tech("XQuery", Set("XQuery"), ProgrammingLanguage),
    Tech("XSB", Set("XSB"), ProgrammingLanguage),
    Tech("XSLT", Set("XSLT"), ProgrammingLanguage),
    Tech("Xtend", Set("Xtend"), ProgrammingLanguage),
    Tech("Yorick", Set("Yorick"), ProgrammingLanguage),
    Tech("YQL", Set("YQL"), ProgrammingLanguage),
    Tech("Zeno", Set("Zeno"), ProgrammingLanguage),
    Tech("ZOPL", Set("ZOPL"), ProgrammingLanguage),
    Tech("ZPL", Set("ZPL"), ProgrammingLanguage),
    Tech("Flutter", Set("Flutter"), ProgrammingLanguage),
    Tech("HTML", Set("HTML5", "HTML"), ProgrammingLanguage),
    Tech("CSS", Set("CSS"), ProgrammingLanguage),
    Tech("OutSystems", Set("Outsystems", "OutSystems"), ProgrammingLanguage),
    // ################# Front-End Stuff #################
    Tech("Sass", Set("Sass", "SCSS"), Other),
    // ################# Platforms #################
    Tech("Node.js", Set("Node.js", "node.js", "NodeJS", "NodeJs", "Nodejs"), Platform),
    Tech(".NET", Set(".NET", ".net", ".Net"), Platform),
    // ################# Infrastructure #################
    Tech("Terraform", Set("Terraform"), InfrastructureTool),
    Tech("Kubernetes", Set("Kubernetes"), InfrastructureTool),
    Tech("Docker", Set("Docker"), InfrastructureTool),
    Tech("Vagrant", Set("Vagrant"), InfrastructureTool),
    Tech("Helm", Set("Helm"), InfrastructureTool),
    Tech("MicroK8s", Set("MicroK8s", "Microk8s"), InfrastructureTool),
    Tech("Chef", Set("Chef"), InfrastructureTool),
    Tech("Puppet", Set("Puppet"), InfrastructureTool),
    Tech("Ansible", Set("Ansible"), InfrastructureTool),
    Tech("VMware", Set("VMWare", "VMware"), InfrastructureTool),
    // ################# Mobile #################
    Tech("iOS", Set("iOS"), Mobile),
    Tech("Android", Set("Android"), Mobile),
    Tech("Cordova", Set("Cordova"), Mobile),
    Tech("React Native", Set("React Native"), Mobile),
    Tech("Xamarin", Set("Xamarin"), Mobile),
    Tech("Ionic", Set("Ionic"), Mobile),
    // ################# Frameworks #################
    Tech("Ruby On Rails", Set("Ruby On Rails", "Rails"), Framework),
    Tech("Play Framework", Set("Play", "Play Framework"), Framework),
    Tech("ASP.NET", Set("ASP.NET"), Framework),
    Tech("Electron", Set("Electron"), Framework),
    // ## Java
    Tech("Spring Framework", Set("Spring Framework", "Spring", "Springboot", "Spring Boot"), Framework),
    Tech("Apache Jena", Set("Apache Jena", "Jena"), Framework),
    Tech("Apache Wicket", Set("Apache Wicket", "Wicket"), Framework),
    Tech("Vert.x", Set("Vert.x"), Framework),
    Tech("Dropwizard", Set("Dropwizard"), Framework),
    // ## Python
    Tech("Twisted", Set("Twisted"), Framework),
    Tech("Pyramid", Set("Pyramid"), Framework),
    Tech("Flask", Set("Flask"), Framework),
    Tech("Django", Set("Django"), Framework),
    Tech("FastAPI", Set("FastAPI"), Framework),
    // ## PHP
    Tech("CakePHP", Set("CakePHP"), Framework),
    Tech("Symfony", Set("Symfony"), Framework),
    Tech("Laravel", Set("Laravel"), Framework),
    Tech("Lumen", Set("Lumen"), Framework),
    Tech("Phalcon", Set("Phalcon"), Framework),
    // ## Javascript
    Tech("Ember.js", Set("Ember", "Ember.js"), Framework),
    Tech("Meteor", Set("Meteor"), Framework),
    Tech("Vue.js", Set("Vue.js"), Framework),
    Tech("Marionette.js", Set("Marionette.js"), Framework),
    Tech("Angular", Set("Angular", "Angular.js"), Framework),
    Tech("Knockout", Set("KnockoutJS", "Knockout.js", "Knockout"), Framework),
    Tech("React", Set("React", "react.js", "React.js"), Framework),
    Tech("Cycle.js", Set("Cycle.js"), Framework),
    Tech("Draft.js", Set("Draft.js"), Framework),
    Tech("Next.js", Set("Next.js"), Framework),
    Tech("Aurelia", Set("Aurelia"), Framework),
    Tech("choo", Set("choo"), Framework),
    Tech("Preact", Set("Preact"), Framework),
    Tech("Hyperapp", Set("Hyperapp"), Framework),
    Tech("Blazor", Set("Blazor"), Framework),
    Tech("Yew", Set("Yew"), Framework),
    Tech("Svelte", Set("Svelte"), Framework),
    // ## CSS
    Tech("Boostrap", Set("Boostrap"), Framework),
    Tech("Materialize", Set("Materialize", "materializecss", "MaterializeCSS"), Framework),
    Tech("normalize.css", Set("normalize.css"), Framework),
    Tech("sanitize.css", Set("sanitize.css"), Framework),
    Tech("minireset.css", Set("minireset.css"), Framework),
    Tech("inuitcss", Set("inuitcss"), Framework),
    Tech("modern-css-reset", Set("modern-css-reset"), Framework),
    Tech("ress", Set("ress"), Framework),
    Tech("modern-normalize", Set("modern-normalize"), Framework),
    Tech("Water.css", Set("Water.css"), Framework),
    Tech("sakura", Set("sakura"), Framework),
    Tech("Marx", Set("Marx"), Framework),
    Tech("Tacit", Set("Tacit"), Framework),
    Tech("awsm.css", Set("awsm.css"), Framework),
    Tech("Milligram", Set("Milligram"), Framework),
    Tech("Picnic CSS", Set("Picnic CSS"), Framework),
    Tech("Wing", Set("Wing"), Framework),
    Tech("Chota", Set("Chota"), Framework),
    Tech("Semantic UI", Set("Semantic UI"), Framework),
    Tech("Bulma", Set("Bulma"), Framework),
    Tech("Foundation", Set("Foundation"), Framework),
    Tech("UIkit", Set("UIkit"), Framework),
    Tech("Spectre.css", Set("Spectre.css"), Framework),
    Tech("Tachyons", Set("Tachyons"), Framework),
    Tech("Primer", Set("Primer"), Framework),
    Tech("Carbon Components", Set("Carbon Components"), Framework),
    Tech("Blaze UI", Set("Blaze UI"), Framework),
    Tech("PatternFly", Set("PatternFly"), Framework),
    Tech("turretcss", Set("turretcss"), Framework),
    Tech("Cirrus", Set("Cirrus"), Framework),
    Tech("HiQ", Set("HiQ"), Framework),
    Tech("Material Components Web", Set("Material Components Web"), Framework),
    Tech("MUI", Set("MUI"), Framework),
    Tech("Propeller", Set("Propeller"), Framework),
    Tech("Tailwind CSS", Set("Tailwind CSS"), Framework),
    Tech("NES.css", Set("NES.css"), Framework),
    Tech("98.css", Set("98.css"), Framework),
    Tech("Gutenberg", Set("Gutenberg"), Framework),
    Tech("Tufte CSS", Set("Tufte CSS"), Framework),
    Tech("Bojler", Set("Bojler"), Framework),
    Tech("Bourbon", Set("Bourbon"), Framework),
    // ################# Libraries #################
    // ## Javascript
    Tech("Backbone.js", Set("Backbone", "Backbone.js"), Library),
    Tech("Polymer", Set("Polymer"), Library),
    Tech("Relay", Set("Relay"), Library),
    Tech("D3", Set("D3"), Library),
    Tech("jQuery", Set("jQuery"), Library),
    Tech("lit-html", Set("lit-html"), Library),
    Tech("WebGL", Set("WebGL"), Library),
    Tech("Redux", Set("Redux"), Library),
    // ## Scala
    Tech("Cats", Set("Cats"), Library),
    Tech("Doobie", Set("Doobie"), Library),
    Tech("fs2", Set("fs2"), Library),
    Tech("Akka", Set("Akka", "akka"), Library),
    // ## Python
    Tech("Pandas", Set("Pandas", "pandas"), Library),
    Tech("Scikit-learn", Set("Scikit-learn", "Scikit-Learn"), Library),
    Tech("NuPIC", Set("NuPIC"), Library),
    Tech("Ramp", Set("Ramp"), Library),
    Tech("NumPy", Set("NumPy", "Numpy"), Library),
    Tech("Pipenv", Set("Pipenv"), Library),
    Tech("TensorFlow", Set("TensorFlow"), Library),
    Tech("PyTorch", Set("PyTorch"), Library),
    Tech("PyBrain", Set("PyBrain"), Library),
    Tech("MILK", Set("MILK"), Library),
    Tech("Keras", Set("Keras"), Library),
    Tech("Pandas", Set("Pandas"), Library),
    Tech("Scipy", Set("Scipy"), Library),
    Tech("Matplotlib", Set("Matplotlib", "MatplotLib"), Library),
    Tech("Theano", Set("Theano"), Library),
    Tech("SymPy", Set("SymPy"), Library),
    Tech("Caffe2", Set("Caffe2"), Library),
    Tech("Seaborn", Set("Seaborn"), Library),
    Tech("Hebel", Set("Hebel"), Library),
    Tech("Chainer", Set("Chainer"), Library),
    Tech("OpenCV Python", Set("OpenCV Python"), Library),
    Tech("Theano", Set("Theano"), Library),
    Tech("NLTK", Set("NLTK"), Library),
    Tech("SQLAlchemy", Set("SQLAlchemy"), Library),
    Tech("Bokeh", Set("Bokeh"), Library),
    // ################# Big Data #################
    Tech("Hadoop", Set("Hadoop"), Other),
    Tech("Apache Spark", Set("Spark", "Apache Spark"), Other),
    Tech("Qlik", Set("Qlik"), Other),
    Tech("Splunk", Set("Splunk"), Other),
    // ################# Databases #################
    Tech("MySQL", Set("MySQL", "mySQL"), Database),
    Tech("SQLAlchemy", Set("SQLAlchemy"), Database),
    Tech("InfluxDB", Set("InfluxDB"), Database),
    Tech("MongoDB", Set("MongoDB"), Database),
    Tech("RethinkDB", Set("RethinkDB"), Database),
    Tech("TinkerPop", Set("TinkerPop"), Database),
    Tech("PostgreSQL", Set("PostgreSQL"), Database),
    Tech("CouchDB", Set("CouchDB"), Database),
    Tech("HBase", Set("HBase"), Database),
    Tech("Contexture", Set("Contexture"), Database),
    Tech("SQL Server", Set("SQL Server", "MSSQL"), Database),
    Tech("DynamoDB", Set("DynamoDB"), Database),
    Tech("Redis", Set("Redis", "redis"), Database),
    Tech("Couchbase", Set("Couchbase"), Database),
    Tech("Apache Cassandra", Set("Cassandra"), Database),
    Tech("Apache HBase", Set("HBase"), Database),
    Tech("Neo4j", Set("Neo4j"), Database),
    Tech("Oracle Database", Set("Oracle Database", "Oracle database"), Database),
    // ################# Build Tools #################
    Tech("Maven", Set("Maven"), BuildTool),
    Tech("Gradle", Set("Gradle"), BuildTool),
    Tech("CMake", Set("CMake"), BuildTool),
    Tech("sbt", Set("sbt"), BuildTool),
    // ################# Test/QA #################
    Tech("Cucumber", Set("Cucumber"), TestAndQA),
    Tech("Selenium", Set("Selenium"), TestAndQA),
    Tech("TestRail", Set("Test Rail", "TestRail"), TestAndQA),
    Tech("BackstopJS", Set("BackstopJS"), TestAndQA),
    Tech("JUnit", Set("JUnit"), TestAndQA),
    Tech("PHPUnit", Set("PHPUnit"), TestAndQA),
    Tech("Sikuli", Set("Sikuli"), TestAndQA),
    Tech("TestLink", Set("TestLink", "TestLink"), TestAndQA),
    Tech("JMeter", Set("JMeter"), TestAndQA),
    Tech("Cypress", Set("Cypress"), TestAndQA),
    Tech("TestCafe", Set("TestCafe"), TestAndQA),
    Tech("SonarQube", Set("SonarQube"), TestAndQA),
    Tech("Protractor", Set("Protractor"), TestAndQA),
    Tech("Jasmine", Set("Jasmine"), TestAndQA),
    // ################# CI/CD #################
    Tech("Abstruse CI", Set("Abstruse CI"), CICD),
    Tech("Agola", Set("Agola"), CICD),
    Tech("Appcircle.io", Set("Appcircle.io"), CICD),
    Tech("Appveyor", Set("Appveyor"), CICD),
    Tech("Assertible", Set("Assertible"), CICD),
    Tech("AWS CodeBuild", Set("AWS CodeBuild"), CICD),
    Tech("Azure DevOps", Set("Azure DevOps"), CICD),
    Tech("Badwolf", Set("Badwolf"), CICD),
    Tech("Bamboo", Set("Bamboo"), CICD),
    Tech("BitBucket Pipelines", Set("BitBucket Pipelines"), CICD),
    Tech("Bitrise", Set("Bitrise"), CICD),
    Tech("Buddy", Set("Buddy"), CICD),
    Tech("builds.sr.ht", Set("builds.sr.ht"), CICD),
    Tech("Buildkite", Set("Buildkite"), CICD),
    Tech("Chrono CI", Set("Chrono CI"), CICD),
    Tech("CircleCI", Set("Circle CI", "CircleCI"), CICD),
    Tech("Cirrus CI", Set("Cirrus CI"), CICD),
    Tech("Codacy", Set("Codacy"), CICD),
    Tech("Code Climate", Set("Code Climate"), CICD),
    Tech("CodeFresh", Set("CodeFresh"), CICD),
    Tech("Codemagic", Set("Codemagic"), CICD),
    Tech("Codeship", Set("Codeship"), CICD),
    Tech("Concourse CI", Set("Concourse CI"), CICD),
    Tech("continuousphp", Set("continuousphp"), CICD),
    Tech("Coveralls", Set("Coveralls"), CICD),
    Tech("Coverity", Set("Coverity"), CICD),
    Tech("Drone", Set("Drone"), CICD),
    Tech("Ebert", Set("Ebert"), CICD),
    Tech("Evergreen", Set("Evergreen"), CICD),
    Tech("flow.ci", Set("flow.ci"), CICD),
    Tech("GoCD", Set("GoCD"), CICD),
    Tech("GitLab", Set("GitLab"), CICD),
    Tech("GitGud", Set("GitGud"), CICD),
    Tech("GitHub Actions", Set("GitHub Actions"), CICD),
    Tech("Hound CI", Set("Hound CI"), CICD),
    Tech("Hydra", Set("Hydra"), CICD),
    Tech("Jenkins", Set("Jenkins"), CICD),
    Tech("Kritika", Set("Kritika"), CICD),
    Tech("minci", Set("minci"), CICD),
    Tech("Peakflow", Set("Peakflow"), CICD),
    Tech("Previs", Set("Previs"), CICD),
    Tech("Probo.CI", Set("Probo.CI"), CICD),
    Tech("RazorOps", Set("RazorOps"), CICD),
    Tech("Saucelabs", Set("Saucelabs"), CICD),
    Tech("Scrutinizer", Set("Scrutinizer"), CICD),
    Tech("Semaphore", Set("Semaphore"), CICD),
    Tech("Shippable", Set("Shippable"), CICD),
    Tech("Sider", Set("Sider"), CICD),
    Tech("Snake CI", Set("Snake CI"), CICD),
    Tech("StyleCI", Set("StyleCI"), CICD),
    Tech("TeamCity", Set("TeamCity"), CICD),
    Tech("Travis CI", Set("Travis CI"), CICD),
    Tech("Wercker", Set("Wercker"), CICD),
    Tech("Zuul", Set("Zuul"), CICD),
    // ################# Cloud #################
    Tech("AWS", Set("Amazon Web Services", "AWS"), Cloud),
    Tech("Azure", Set("Azure"), Cloud),
    Tech("IBM Cloud", Set("IBM Cloud"), Cloud),
    Tech("Digital Ocean", Set("Digital Ocean"), Cloud),
    Tech("Heroku", Set("Heroku"), Cloud),
    // ################# Query Languages #################
    Tech("XPath", Set("XPath"), QueryLanguage),
    // ################# Tools #################
    Tech("Postman", Set("Postman"), Tool),
    Tech("DbVisualizer", Set("DbVisualizer"), Tool),
    Tech("Hibernate", Set("Hibernate"), Tool),
    Tech("Google Web Toolkit", Set("Google Web Toolkit", "GWT"), Tool),
    Tech("PostCSS", Set("PostCSS"), Tool),
    Tech("webpack", Set("webpack"), Tool),
    Tech("Browserify", Set("Browserify"), Tool),
    Tech("Prometheus", Set("Prometheus"), Tool),
    Tech("Thanos", Set("Thanos"), Tool),
    Tech("Loki", Set("Loki"), Tool),
    Tech("Elasticsearch", Set("Elasticsearch", "Elastic Search"), Tool),
    Tech("Kibana", Set("Kibana"), Tool),
    Tech("Graylog", Set("Graylog"), Tool),
    Tech("ReportPortal", Set("ReportPortal"), Tool),
    Tech("Git", Set("Git"), Tool),
    Tech("Kafka", Set("Kafka"), Tool),
    Tech("Chartio", Set("Chartio"), Tool),
    Tech("LaunchDarkly", Set("LaunchDarkly"), Tool),
    Tech("Apache Tomcat", Set("Tomcat"), Tool),
    Tech("DBeaver", Set("DBeaver"), Tool),
    Tech("ActiveMQ", Set("ActiveMQ", "AMQ"), Tool),
    Tech("TIBCO StreamBase", Set("StreamBase", "Streambase", "TIBCO StreamBase"), Tool),
    Tech("Grafana", Set("Grafana"), Tool),
    Tech("Tableau", Set("Tableau"), Tool),
    Tech("Excel", Set("Excel"), Tool),
    // ################# Operating Systems #################
    Tech("Windows", Set("Windows"), OperatingSystem),
    Tech("Linux", Set("Linux"), OperatingSystem),
    Tech("Red Hat", Set("Red Hat"), OperatingSystem),
  )

  def fromName(name: String): Option[Tech] =
    all.find(_.name == name)

  //println(s"Duplicated tech: ${all.groupBy(_.name).values.filter(_.size > 1)}")
}
