package com.lcampos.duration_per_tech

import com.lcampos.duration_per_tech.TechCategory._

case class Tech(
  name: String,
  canonName: String,
  category: TechCategory
)

sealed trait TechCategory {
  val uiRepresentation: String
  val priorityInOrdering: Int // Lower is means first in order
}

object TechCategory {
  case object ProgrammingLanguage extends TechCategory {
    val uiRepresentation: String = "Programming Languages"
    val priorityInOrdering: Int = 1
  }

  case object Framework extends TechCategory {
    val uiRepresentation: String = "Frameworks"
    val priorityInOrdering: Int = 2
  }

  case object Platform extends TechCategory {
    val uiRepresentation: String = "Platforms"
    val priorityInOrdering: Int = 3
  }

  case object Library extends TechCategory {
    val uiRepresentation: String = "Libraries"
    val priorityInOrdering: Int = 4
  }

  case object Mobile extends TechCategory {
    val uiRepresentation: String = "Mobile"
    val priorityInOrdering: Int = 5
  }

  case object Database extends TechCategory {
    val uiRepresentation: String = "Databases"
    val priorityInOrdering: Int = 6
  }

  case object CICD extends TechCategory {
    val uiRepresentation: String = "CI/CD"
    val priorityInOrdering: Int = 7
  }

  case object Cloud extends TechCategory {
    val uiRepresentation: String = "Cloud"
    val priorityInOrdering: Int = 8
  }

  case object InfrastructureTool extends TechCategory {
    val uiRepresentation: String = "Infrastructure Tools"
    val priorityInOrdering: Int = 9
  }

  case object QueryLanguage extends TechCategory {
    val uiRepresentation: String = "Query Languages"
    val priorityInOrdering: Int = 10
  }

  case object TestAndQA extends TechCategory {
    val uiRepresentation: String = "Test and QA"
    val priorityInOrdering: Int = 11
  }

  case object BuildTool extends TechCategory {
    val uiRepresentation: String = "Build Tools"
    val priorityInOrdering: Int = 12
  }

  case object Tool extends TechCategory {
    val uiRepresentation: String = "Tools"
    val priorityInOrdering: Int = 13
  }

  case object Other extends TechCategory {
    val uiRepresentation: String = "Other"
    val priorityInOrdering: Int = 14
  }

  implicit def techCategoryOrdering: Ordering[TechCategory] = (x: TechCategory, y: TechCategory) =>
    x.priorityInOrdering compare y.priorityInOrdering
}


object TechList {

  /**
   * Sources:
   * - https://github.com/sindresorhus/awesome
   */

  val all: List[Tech] = List(
    // ################# Programming languages #################
    Tech("A#", "A#", ProgrammingLanguage),
    Tech("A+", "A+", ProgrammingLanguage),
    Tech("A++", "A++", ProgrammingLanguage),
    Tech("ABAP", "ABAP", ProgrammingLanguage),
    Tech("ABC", "ABC", ProgrammingLanguage),
    Tech("ABC ALGOL", "ABC ALGOL", ProgrammingLanguage),
    Tech("ABSET", "ABSET", ProgrammingLanguage),
    Tech("ABSYS", "ABSYS", ProgrammingLanguage),
    Tech("ACC", "ACC", ProgrammingLanguage),
    Tech("Accent", "Accent", ProgrammingLanguage),
    Tech("ACL2", "ACL2", ProgrammingLanguage),
    Tech("ACT-III", "ACT-III", ProgrammingLanguage),
    Tech("Action!", "Action!", ProgrammingLanguage),
    Tech("ActionScript", "ActionScript", ProgrammingLanguage),
    Tech("Ada", "Ada", ProgrammingLanguage),
    Tech("Adenine", "Adenine", ProgrammingLanguage),
    Tech("Agda", "Agda", ProgrammingLanguage),
    Tech("Agilent VEE", "Agilent VEE", ProgrammingLanguage),
    Tech("AIMMS", "AIMMS", ProgrammingLanguage),
    Tech("Alef", "Alef", ProgrammingLanguage),
    Tech("ALF", "ALF", ProgrammingLanguage),
    Tech("ALGOL 58", "ALGOL 58", ProgrammingLanguage),
    Tech("ALGOL 60", "ALGOL 60", ProgrammingLanguage),
    Tech("ALGOL 68", "ALGOL 68", ProgrammingLanguage),
    Tech("Alice", "Alice", ProgrammingLanguage),
    Tech("AmbientTalk", "AmbientTalk", ProgrammingLanguage),
    Tech("AMOS", "AMOS", ProgrammingLanguage),
    Tech("AMPL", "AMPL", ProgrammingLanguage),
    Tech("APL", "APL", ProgrammingLanguage),
    Tech("AppleScript", "AppleScript", ProgrammingLanguage),
    Tech("Arc", "Arc", ProgrammingLanguage),
    Tech("ARexx", "ARexx", ProgrammingLanguage),
    Tech("Argus", "Argus", ProgrammingLanguage),
    Tech("AspectJ", "AspectJ", ProgrammingLanguage),
    Tech("Assembly Language", "Assembly language", ProgrammingLanguage),
    Tech("ATS", "ATS", ProgrammingLanguage),
    Tech("Ateji PX", "Ateji PX", ProgrammingLanguage),
    Tech("AutoHotkey", "AutoHotkey", ProgrammingLanguage),
    Tech("Autocoder", "Autocoder", ProgrammingLanguage),
    Tech("AutoIt", "AutoIt", ProgrammingLanguage),
    Tech("Averest", "Averest", ProgrammingLanguage),
    Tech("AWK", "AWK", ProgrammingLanguage),
    Tech("Axum", "Axum", ProgrammingLanguage),
    Tech("Babbage", "Babbage", ProgrammingLanguage),
    Tech("Bash", "Bash", ProgrammingLanguage),
    Tech("BASIC", "BASIC", ProgrammingLanguage),
    Tech("bc", "bc", ProgrammingLanguage),
    Tech("BCPL", "BCPL", ProgrammingLanguage),
    Tech("BeanShell", "BeanShell", ProgrammingLanguage),
    Tech("Batch (Windows/Dos)", "Batch (Windows/Dos)", ProgrammingLanguage),
    Tech("Bertrand", "Bertrand", ProgrammingLanguage),
    Tech("BETA", "BETA", ProgrammingLanguage),
    Tech("Bigwig", "Bigwig", ProgrammingLanguage),
    Tech("Bistro", "Bistro", ProgrammingLanguage),
    Tech("BitC", "BitC", ProgrammingLanguage),
    Tech("BLISS", "BLISS", ProgrammingLanguage),
    Tech("Blue", "Blue", ProgrammingLanguage),
    Tech("Bon", "Bon", ProgrammingLanguage),
    Tech("Boo", "Boo", ProgrammingLanguage),
    Tech("Boomerang", "Boomerang", ProgrammingLanguage),
    Tech("Bourne shell", "Bourne shell", ProgrammingLanguage),
    Tech("bash", "bash", ProgrammingLanguage),
    Tech("ksh", "ksh", ProgrammingLanguage),
    Tech("BREW", "BREW", ProgrammingLanguage),
    Tech("BPEL", "BPEL", ProgrammingLanguage),
    Tech("C", "C", ProgrammingLanguage),
    Tech("C--", "C--", ProgrammingLanguage),
    Tech("C++", "C++", ProgrammingLanguage),
    Tech("C#", "C#", ProgrammingLanguage),
    Tech("C/AL", "C/AL", ProgrammingLanguage),
    Tech("Caché ObjectScript", "Caché ObjectScript", ProgrammingLanguage),
    Tech("C Shell", "C Shell", ProgrammingLanguage),
    Tech("Caml", "Caml", ProgrammingLanguage),
    Tech("Candle", "Candle", ProgrammingLanguage),
    Tech("Cayenne", "Cayenne", ProgrammingLanguage),
    Tech("CDuce", "CDuce", ProgrammingLanguage),
    Tech("Cecil", "Cecil", ProgrammingLanguage),
    Tech("Cel", "Cel", ProgrammingLanguage),
    Tech("Cesil", "Cesil", ProgrammingLanguage),
    Tech("Ceylon", "Ceylon", ProgrammingLanguage),
    Tech("CFEngine", "CFEngine", ProgrammingLanguage),
    Tech("CFML", "CFML", ProgrammingLanguage),
    Tech("Chapel", "Chapel", ProgrammingLanguage),
    Tech("CHIP-8", "CHIP-8", ProgrammingLanguage),
    Tech("chomski", "chomski", ProgrammingLanguage),
    Tech("ChucK", "ChucK", ProgrammingLanguage),
    Tech("CICS", "CICS", ProgrammingLanguage),
    Tech("Cilk", "Cilk", ProgrammingLanguage),
    Tech("CL", "CL", ProgrammingLanguage),
    Tech("Claire", "Claire", ProgrammingLanguage),
    Tech("Clarion", "Clarion", ProgrammingLanguage),
    Tech("Clipper", "Clipper", ProgrammingLanguage),
    Tech("CLIST", "CLIST", ProgrammingLanguage),
    Tech("Clojure", "Clojure", ProgrammingLanguage),
    Tech("CMS-2", "CMS-2", ProgrammingLanguage),
    Tech("COBOL", "COBOL", ProgrammingLanguage),
    Tech("Cobra", "Cobra", ProgrammingLanguage),
    Tech("CoffeeScript", "CoffeeScript", ProgrammingLanguage),
    Tech("ColdC", "ColdC", ProgrammingLanguage),
    Tech("ColdFusion", "ColdFusion", ProgrammingLanguage),
    Tech("COMAL", "COMAL", ProgrammingLanguage),
    Tech("COMIT", "COMIT", ProgrammingLanguage),
    Tech("Common Lisp", "Common Lisp", ProgrammingLanguage),
    Tech("COMPASS", "COMPASS", ProgrammingLanguage),
    Tech("Component Pascal", "Component Pascal", ProgrammingLanguage),
    Tech("Converge", "Converge", ProgrammingLanguage),
    Tech("Coq", "Coq", ProgrammingLanguage),
    Tech("Coral 66", "Coral 66", ProgrammingLanguage),
    Tech("Corn", "Corn", ProgrammingLanguage),
    Tech("CorVision", "CorVision", ProgrammingLanguage),
    Tech("COWSEL", "COWSEL", ProgrammingLanguage),
    Tech("CPL", "CPL", ProgrammingLanguage),
    Tech("csh", "csh", ProgrammingLanguage),
    Tech("CSP", "CSP", ProgrammingLanguage),
    Tech("Csound", "Csound", ProgrammingLanguage),
    Tech("CUDA", "CUDA", ProgrammingLanguage),
    Tech("Curl", "Curl", ProgrammingLanguage),
    Tech("Curry", "Curry", ProgrammingLanguage),
    Tech("Cyclone", "Cyclone", ProgrammingLanguage),
    Tech("Cython", "Cython", ProgrammingLanguage),
    Tech("DASL", "DASL", ProgrammingLanguage),
    Tech("DASL", "DASL", ProgrammingLanguage),
    Tech("Dart", "Dart", ProgrammingLanguage),
    Tech("DataFlex", "DataFlex", ProgrammingLanguage),
    Tech("Datalog", "Datalog", ProgrammingLanguage),
    Tech("DATATRIEVE", "DATATRIEVE", ProgrammingLanguage),
    Tech("dBase", "dBase", ProgrammingLanguage),
    Tech("dc", "dc", ProgrammingLanguage),
    Tech("DCL", "DCL", ProgrammingLanguage),
    Tech("Deesel", "Deesel", ProgrammingLanguage),
    Tech("Delphi", "Delphi", ProgrammingLanguage),
    Tech("DinkC", "DinkC", ProgrammingLanguage),
    Tech("DIBOL", "DIBOL", ProgrammingLanguage),
    Tech("Dog", "Dog", ProgrammingLanguage),
    Tech("Draco", "Draco", ProgrammingLanguage),
    Tech("DRAKON", "DRAKON", ProgrammingLanguage),
    Tech("Dylan", "Dylan", ProgrammingLanguage),
    Tech("DYNAMO", "DYNAMO", ProgrammingLanguage),
    Tech("E#", "E#", ProgrammingLanguage),
    Tech("Ease", "Ease", ProgrammingLanguage),
    Tech("ECMAScript", "ECMAScript", ProgrammingLanguage),
    Tech("Edinburgh IMP", "Edinburgh IMP", ProgrammingLanguage),
    Tech("EGL", "EGL", ProgrammingLanguage),
    Tech("Eiffel", "Eiffel", ProgrammingLanguage),
    Tech("ELAN", "ELAN", ProgrammingLanguage),
    Tech("Elixir", "Elixir", ProgrammingLanguage),
    Tech("Elm", "Elm", ProgrammingLanguage),
    Tech("Emacs Lisp", "Emacs Lisp", ProgrammingLanguage),
    Tech("Emerald", "Emerald", ProgrammingLanguage),
    Tech("Epigram", "Epigram", ProgrammingLanguage),
    Tech("EPL", "EPL", ProgrammingLanguage),
    Tech("Erlang", "Erlang", ProgrammingLanguage),
    Tech("Escapade", "Escapade", ProgrammingLanguage),
    Tech("Escher", "Escher", ProgrammingLanguage),
    Tech("ESPOL", "ESPOL", ProgrammingLanguage),
    Tech("Esterel", "Esterel", ProgrammingLanguage),
    Tech("Etoys", "Etoys", ProgrammingLanguage),
    Tech("Euclid", "Euclid", ProgrammingLanguage),
    Tech("Euler", "Euler", ProgrammingLanguage),
    Tech("Euphoria", "Euphoria", ProgrammingLanguage),
    Tech("EusLisp", "EusLisp", ProgrammingLanguage),
    Tech("CMS EXEC", "CMS EXEC", ProgrammingLanguage),
    Tech("EXEC 2", "EXEC 2", ProgrammingLanguage),
    Tech("Executable UML", "Executable UML", ProgrammingLanguage),
    Tech("F#", "F#", ProgrammingLanguage),
    Tech("Factor", "Factor", ProgrammingLanguage),
    Tech("Falcon", "Falcon", ProgrammingLanguage),
    Tech("Fancy", "Fancy", ProgrammingLanguage),
    Tech("Fantom", "Fantom", ProgrammingLanguage),
    Tech("FAUST", "FAUST", ProgrammingLanguage),
    Tech("Felix", "Felix", ProgrammingLanguage),
    Tech("Ferite", "Ferite", ProgrammingLanguage),
    Tech("FFP", "FFP", ProgrammingLanguage),
    Tech("Fjölnir", "Fjölnir", ProgrammingLanguage),
    Tech("FL", "FL", ProgrammingLanguage),
    Tech("Flavors", "Flavors", ProgrammingLanguage),
    Tech("Flex", "Flex", ProgrammingLanguage),
    Tech("FOCAL", "FOCAL", ProgrammingLanguage),
    Tech("FOCUS", "FOCUS", ProgrammingLanguage),
    Tech("FOIL", "FOIL", ProgrammingLanguage),
    Tech("FORMAC", "FORMAC", ProgrammingLanguage),
    Tech("@Formula", "@Formula", ProgrammingLanguage),
    Tech("Forth", "Forth", ProgrammingLanguage),
    Tech("Fortran", "Fortran", ProgrammingLanguage),
    Tech("Fortress", "Fortress", ProgrammingLanguage),
    Tech("FoxBase", "FoxBase", ProgrammingLanguage),
    Tech("FoxPro", "FoxPro", ProgrammingLanguage),
    Tech("FPr", "FPr", ProgrammingLanguage),
    Tech("Franz Lisp", "Franz Lisp", ProgrammingLanguage),
    Tech("Frege", "Frege", ProgrammingLanguage),
    Tech("F-script", "F-Script", ProgrammingLanguage),
    Tech("FSProg", "FSProg", ProgrammingLanguage),
    Tech("Google Apps Script", "Google Apps Script", ProgrammingLanguage),
    Tech("Game Maker Language", "Game Maker Language", ProgrammingLanguage),
    Tech("GameMonkey Script", "GameMonkey Script", ProgrammingLanguage),
    Tech("GAMS", "GAMS", ProgrammingLanguage),
    Tech("G-code", "G-code", ProgrammingLanguage),
    Tech("Genie", "Genie", ProgrammingLanguage),
    Tech("GDL", "GDL", ProgrammingLanguage),
    Tech("Gibiane", "Gibiane", ProgrammingLanguage),
    Tech("GJ", "GJ", ProgrammingLanguage),
    Tech("GEORGE", "GEORGE", ProgrammingLanguage),
    Tech("GLSL", "GLSL", ProgrammingLanguage),
    Tech("GNU E", "GNU E", ProgrammingLanguage),
    Tech("GM", "GM", ProgrammingLanguage),
    Tech("golang", "Golang", ProgrammingLanguage),
    Tech("Golang", "Golang", ProgrammingLanguage),
    Tech("Go", "Golang", ProgrammingLanguage),
    Tech("Go!", "Go!", ProgrammingLanguage),
    Tech("Gödel", "Gödel", ProgrammingLanguage),
    Tech("Godiva", "Godiva", ProgrammingLanguage),
    Tech("GOM (Good Old Mad)", "GOM (Good Old Mad)", ProgrammingLanguage),
    Tech("Goo", "Goo", ProgrammingLanguage),
    Tech("Gosu", "Gosu", ProgrammingLanguage),
    Tech("GOTRAN", "GOTRAN", ProgrammingLanguage),
    Tech("GPSS", "GPSS", ProgrammingLanguage),
    Tech("GraphTalk", "GraphTalk", ProgrammingLanguage),
    Tech("GRASS", "GRASS", ProgrammingLanguage),
    Tech("Groovy", "Groovy", ProgrammingLanguage),
    Tech("Hack", "Hack", ProgrammingLanguage),
    Tech("HAL/S", "HAL/S", ProgrammingLanguage),
    Tech("Hamilton C shell", "Hamilton C shell", ProgrammingLanguage),
    Tech("Harbour", "Harbour", ProgrammingLanguage),
    Tech("Hartmann pipelines", "Hartmann pipelines", ProgrammingLanguage),
    Tech("Haskell", "Haskell", ProgrammingLanguage),
    Tech("Haxe", "Haxe", ProgrammingLanguage),
    Tech("High Level Assembly", "High Level Assembly", ProgrammingLanguage),
    Tech("HLSL", "HLSL", ProgrammingLanguage),
    Tech("Hop", "Hop", ProgrammingLanguage),
    Tech("Hope", "Hope", ProgrammingLanguage),
    Tech("Hugo", "Hugo", ProgrammingLanguage),
    Tech("Hume", "Hume", ProgrammingLanguage),
    Tech("HyperTalk", "HyperTalk", ProgrammingLanguage),
    Tech("IBM Basic assembly language", "IBM Basic assembly language", ProgrammingLanguage),
    Tech("IBM HAScript", "IBM HAScript", ProgrammingLanguage),
    Tech("IBM Informix-4GL", "IBM Informix-4GL", ProgrammingLanguage),
    Tech("IBM RPG", "IBM RPG", ProgrammingLanguage),
    Tech("ICI", "ICI", ProgrammingLanguage),
    Tech("Icon", "Icon", ProgrammingLanguage),
    Tech("IDL", "IDL", ProgrammingLanguage),
    Tech("Idris", "Idris", ProgrammingLanguage),
    Tech("IMP", "IMP", ProgrammingLanguage),
    Tech("Inform", "Inform", ProgrammingLanguage),
    Tech("Io", "Io", ProgrammingLanguage),
    Tech("Ioke", "Ioke", ProgrammingLanguage),
    Tech("IPL", "IPL", ProgrammingLanguage),
    Tech("IPTSCRAE", "IPTSCRAE", ProgrammingLanguage),
    Tech("ISLISP", "ISLISP", ProgrammingLanguage),
    Tech("ISPF", "ISPF", ProgrammingLanguage),
    Tech("ISWIM", "ISWIM", ProgrammingLanguage),
    Tech("J#", "J#", ProgrammingLanguage),
    Tech("J++", "J++", ProgrammingLanguage),
    Tech("JADE", "JADE", ProgrammingLanguage),
    Tech("Jako", "Jako", ProgrammingLanguage),
    Tech("JAL", "JAL", ProgrammingLanguage),
    Tech("Janus", "Janus", ProgrammingLanguage),
    Tech("JASS", "JASS", ProgrammingLanguage),
    Tech("JAVA", "Java", ProgrammingLanguage),
    Tech("Java", "Java", ProgrammingLanguage),
    Tech("Java8", "Java", ProgrammingLanguage),
    Tech("JavaEE", "Java", ProgrammingLanguage),
    Tech("JavaScript", "JavaScript", ProgrammingLanguage),
    Tech("Javascript", "JavaScript", ProgrammingLanguage),
    Tech("JCL", "JCL", ProgrammingLanguage),
    Tech("JEAN", "JEAN", ProgrammingLanguage),
    Tech("Join Java", "Join Java", ProgrammingLanguage),
    Tech("JOSS", "JOSS", ProgrammingLanguage),
    Tech("Joule", "Joule", ProgrammingLanguage),
    Tech("JOVIAL", "JOVIAL", ProgrammingLanguage),
    Tech("Joy", "Joy", ProgrammingLanguage),
    Tech("JScript", "JScript", ProgrammingLanguage),
    Tech("JScript .NET", "JScript .NET", ProgrammingLanguage),
    Tech("JavaFX Script", "JavaFX Script", ProgrammingLanguage),
    Tech("Julia", "Julia", ProgrammingLanguage),
    Tech("Jython", "Jython", ProgrammingLanguage),
    Tech("Kaleidoscope", "Kaleidoscope", ProgrammingLanguage),
    Tech("Karel", "Karel", ProgrammingLanguage),
    Tech("Karel++", "Karel++", ProgrammingLanguage),
    Tech("KEE", "KEE", ProgrammingLanguage),
    Tech("Kixtart", "Kixtart", ProgrammingLanguage),
    Tech("KIF", "KIF", ProgrammingLanguage),
    Tech("Kojo", "Kojo", ProgrammingLanguage),
    Tech("Kotlin", "Kotlin", ProgrammingLanguage),
    Tech("KRC", "KRC", ProgrammingLanguage),
    Tech("KRL", "KRL", ProgrammingLanguage),
    Tech("KUKA", "KUKA", ProgrammingLanguage),
    Tech("KRYPTON", "KRYPTON", ProgrammingLanguage),
    Tech("ksh", "ksh", ProgrammingLanguage),
    Tech("et# .net", "L# .NET", ProgrammingLanguage),
    Tech("LabVIEW", "LabVIEW", ProgrammingLanguage),
    Tech("Ladder", "Ladder", ProgrammingLanguage),
    Tech("Lagoona", "Lagoona", ProgrammingLanguage),
    Tech("LANSA", "LANSA", ProgrammingLanguage),
    Tech("Lasso", "Lasso", ProgrammingLanguage),
    Tech("LaTeX", "LaTeX", ProgrammingLanguage),
    Tech("Lava", "Lava", ProgrammingLanguage),
    Tech("LC-3", "LC-3", ProgrammingLanguage),
    Tech("Leda", "Leda", ProgrammingLanguage),
    Tech("Legoscript", "Legoscript", ProgrammingLanguage),
    Tech("LIL", "LIL", ProgrammingLanguage),
    Tech("LilyPond", "LilyPond", ProgrammingLanguage),
    Tech("Limbo", "Limbo", ProgrammingLanguage),
    Tech("Limnor", "Limnor", ProgrammingLanguage),
    Tech("LINC", "LINC", ProgrammingLanguage),
    Tech("Lingo", "Lingo", ProgrammingLanguage),
    Tech("Linoleum", "Linoleum", ProgrammingLanguage),
    Tech("LIS", "LIS", ProgrammingLanguage),
    Tech("LISA", "LISA", ProgrammingLanguage),
    Tech("Lisaac", "Lisaac", ProgrammingLanguage),
    Tech("Lisp", "Lisp", ProgrammingLanguage),
    Tech("Lite-C", "Lite-C", ProgrammingLanguage),
    Tech("Lithe", "Lithe", ProgrammingLanguage),
    Tech("Little b", "Little b", ProgrammingLanguage),
    Tech("Logo", "Logo", ProgrammingLanguage),
    Tech("Logtalk", "Logtalk", ProgrammingLanguage),
    Tech("LPC", "LPC", ProgrammingLanguage),
    Tech("LSE", "LSE", ProgrammingLanguage),
    Tech("LSL", "LSL", ProgrammingLanguage),
    Tech("LiveCode", "LiveCode", ProgrammingLanguage),
    Tech("LiveScript", "LiveScript", ProgrammingLanguage),
    Tech("Lua", "Lua", ProgrammingLanguage),
    Tech("Lucid", "Lucid", ProgrammingLanguage),
    Tech("Lustre", "Lustre", ProgrammingLanguage),
    Tech("LYaPAS", "LYaPAS", ProgrammingLanguage),
    Tech("Lynx", "Lynx", ProgrammingLanguage),
    Tech("M2001", "M2001", ProgrammingLanguage),
    Tech("M4", "M4", ProgrammingLanguage),
    Tech("MAD/I", "MAD/I", ProgrammingLanguage),
    Tech("Magik", "Magik", ProgrammingLanguage),
    Tech("Magma", "Magma", ProgrammingLanguage),
    Tech("Maple", "Maple", ProgrammingLanguage),
    Tech("MAPPER", "MAPPER", ProgrammingLanguage),
    Tech(",-iv", "MARK-IV", ProgrammingLanguage),
    Tech("Mary", "Mary", ProgrammingLanguage),
    Tech("Mathematica", "Mathematica", ProgrammingLanguage),
    Tech("MATLAB", "MATLAB", ProgrammingLanguage),
    Tech("Maxima", "Maxima", ProgrammingLanguage),
    Tech("Macsyma", "Macsyma", ProgrammingLanguage),
    Tech("MaxScript", "MaxScript", ProgrammingLanguage),
    Tech("MDL", "MDL", ProgrammingLanguage),
    Tech("Mercury", "Mercury", ProgrammingLanguage),
    Tech("Mesa", "Mesa", ProgrammingLanguage),
    Tech("Metacard", "Metacard", ProgrammingLanguage),
    Tech("Metafont", "Metafont", ProgrammingLanguage),
    Tech("MetaL", "MetaL", ProgrammingLanguage),
    Tech("Microcode", "Microcode", ProgrammingLanguage),
    Tech("MicroScript", "MicroScript", ProgrammingLanguage),
    Tech("MIIS", "MIIS", ProgrammingLanguage),
    Tech("MillScript", "MillScript", ProgrammingLanguage),
    Tech("MIMIC", "MIMIC", ProgrammingLanguage),
    Tech("Mirah", "Mirah", ProgrammingLanguage),
    Tech("Miranda", "Miranda", ProgrammingLanguage),
    Tech("ML", "ML", ProgrammingLanguage),
    Tech("Moby", "Moby", ProgrammingLanguage),
    Tech("Modelica", "Modelica", ProgrammingLanguage),
    Tech("Mohol", "Mohol", ProgrammingLanguage),
    Tech("MOO", "MOO", ProgrammingLanguage),
    Tech("Mortran", "Mortran", ProgrammingLanguage),
    Tech("Mouse", "Mouse", ProgrammingLanguage),
    Tech("MPD", "MPD", ProgrammingLanguage),
    Tech("CIL", "CIL", ProgrammingLanguage),
    Tech("MSL", "MSL", ProgrammingLanguage),
    Tech("MUMPS", "MUMPS", ProgrammingLanguage),
    Tech("NASM", "NASM", ProgrammingLanguage),
    Tech("NATURAL", "NATURAL", ProgrammingLanguage),
    Tech("Napier88", "Napier88", ProgrammingLanguage),
    Tech("Neko", "Neko", ProgrammingLanguage),
    Tech("Nemerle", "Nemerle", ProgrammingLanguage),
    Tech("nesC", "nesC", ProgrammingLanguage),
    Tech("NESL", "NESL", ProgrammingLanguage),
    Tech("Net.Data", "Net.Data", ProgrammingLanguage),
    Tech("NetLogo", "NetLogo", ProgrammingLanguage),
    Tech("NetRexx", "NetRexx", ProgrammingLanguage),
    Tech("NewLISP", "NewLISP", ProgrammingLanguage),
    Tech("NEWP", "NEWP", ProgrammingLanguage),
    Tech("Newspeak", "Newspeak", ProgrammingLanguage),
    Tech("NewtonScript", "NewtonScript", ProgrammingLanguage),
    Tech("NGL", "NGL", ProgrammingLanguage),
    Tech("Nial", "Nial", ProgrammingLanguage),
    Tech("Nickle", "Nickle", ProgrammingLanguage),
    Tech("Nim", "Nim", ProgrammingLanguage),
    Tech("NPL", "NPL", ProgrammingLanguage),
    Tech("Not eXactly C", "Not eXactly C", ProgrammingLanguage),
    Tech("Not Quite C", "Not Quite C", ProgrammingLanguage),
    Tech("NSIS", "NSIS", ProgrammingLanguage),
    Tech("Nu", "Nu", ProgrammingLanguage),
    Tech("NWScript", "NWScript", ProgrammingLanguage),
    Tech("Oak", "Oak", ProgrammingLanguage),
    Tech("Oberon", "Oberon", ProgrammingLanguage),
    Tech("Obix", "Obix", ProgrammingLanguage),
    Tech("OBJ2", "OBJ2", ProgrammingLanguage),
    Tech("Object Lisp", "Object Lisp", ProgrammingLanguage),
    Tech("ObjectLOGO", "ObjectLOGO", ProgrammingLanguage),
    Tech("Object REXX", "Object REXX", ProgrammingLanguage),
    Tech("Object Pascal", "Object Pascal", ProgrammingLanguage),
    Tech("Objective-C", "Objective-C", ProgrammingLanguage),
    Tech("Objective-J", "Objective-J", ProgrammingLanguage),
    Tech("Obliq", "Obliq", ProgrammingLanguage),
    Tech("Obol", "Obol", ProgrammingLanguage),
    Tech("OCaml", "OCaml", ProgrammingLanguage),
    Tech("occam", "occam", ProgrammingLanguage),
    Tech("occam-π", "occam-π", ProgrammingLanguage),
    Tech("Octave", "Octave", ProgrammingLanguage),
    Tech("OmniMark", "OmniMark", ProgrammingLanguage),
    Tech("Onyx", "Onyx", ProgrammingLanguage),
    Tech("Opa", "Opa", ProgrammingLanguage),
    Tech("Opal", "Opal", ProgrammingLanguage),
    Tech("OpenCL", "OpenCL", ProgrammingLanguage),
    Tech("OpenEdge ABL", "OpenEdge ABL", ProgrammingLanguage),
    Tech("OPL", "OPL", ProgrammingLanguage),
    Tech("OPS5", "OPS5", ProgrammingLanguage),
    Tech("OptimJ", "OptimJ", ProgrammingLanguage),
    Tech("Orc", "Orc", ProgrammingLanguage),
    Tech("ORCA/Modula-2", "ORCA/Modula-2", ProgrammingLanguage),
    Tech("Oriel", "Oriel", ProgrammingLanguage),
    Tech("Orwell", "Orwell", ProgrammingLanguage),
    Tech("Oxygene", "Oxygene", ProgrammingLanguage),
    Tech("Oz", "Oz", ProgrammingLanguage),
    Tech("P#", "P#", ProgrammingLanguage),
    Tech("ParaSail", "ParaSail", ProgrammingLanguage),
    Tech("PARI/GP", "PARI/GP", ProgrammingLanguage),
    Tech("Pascal", "Pascal", ProgrammingLanguage),
    Tech("Pawn", "Pawn", ProgrammingLanguage),
    Tech("PCASTL", "PCASTL", ProgrammingLanguage),
    Tech("PCF", "PCF", ProgrammingLanguage),
    Tech("PEARL", "PEARL", ProgrammingLanguage),
    Tech("PeopleCode", "PeopleCode", ProgrammingLanguage),
    Tech("Perl", "Perl", ProgrammingLanguage),
    Tech("PDL", "PDL", ProgrammingLanguage),
    Tech("PHP", "PHP", ProgrammingLanguage),
    Tech("Phrogram", "Phrogram", ProgrammingLanguage),
    Tech("Pico", "Pico", ProgrammingLanguage),
    Tech("Picolisp", "Picolisp", ProgrammingLanguage),
    Tech("Pict", "Pict", ProgrammingLanguage),
    Tech("Pike", "Pike", ProgrammingLanguage),
    Tech("PIKT", "PIKT", ProgrammingLanguage),
    Tech("PILOT", "PILOT", ProgrammingLanguage),
    Tech("Pipelines", "Pipelines", ProgrammingLanguage),
    Tech("Pizza", "Pizza", ProgrammingLanguage),
    Tech("PL-11", "PL-11", ProgrammingLanguage),
    Tech("PL/0", "PL/0", ProgrammingLanguage),
    Tech("PL/B", "PL/B", ProgrammingLanguage),
    Tech("PL/C", "PL/C", ProgrammingLanguage),
    Tech("PL/I", "PL/I", ProgrammingLanguage),
    Tech("PL/M", "PL/M", ProgrammingLanguage),
    Tech("PL/P", "PL/P", ProgrammingLanguage),
    Tech("PL/SQL", "PL/SQL", ProgrammingLanguage),
    Tech("PL360", "PL360", ProgrammingLanguage),
    Tech("PLANC", "PLANC", ProgrammingLanguage),
    Tech("Plankalkül", "Plankalkül", ProgrammingLanguage),
    Tech("Planner", "Planner", ProgrammingLanguage),
    Tech("PLEX", "PLEX", ProgrammingLanguage),
    Tech("PLEXIL", "PLEXIL", ProgrammingLanguage),
    Tech("Plus", "Plus", ProgrammingLanguage),
    Tech("POP-11", "POP-11", ProgrammingLanguage),
    Tech("PostScript", "PostScript", ProgrammingLanguage),
    Tech("PortablE", "PortablE", ProgrammingLanguage),
    Tech("Powerhouse", "Powerhouse", ProgrammingLanguage),
    Tech("PowerBuilder", "PowerBuilder", ProgrammingLanguage),
    Tech("PowerShell", "PowerShell", ProgrammingLanguage),
    Tech("PPL", "PPL", ProgrammingLanguage),
    Tech("Processing.js", "Processing.js", ProgrammingLanguage),
    Tech("Prograph", "Prograph", ProgrammingLanguage),
    Tech("PROIV", "PROIV", ProgrammingLanguage),
    Tech("Prolog", "Prolog", ProgrammingLanguage),
    Tech("PROMAL", "PROMAL", ProgrammingLanguage),
    Tech("Promela", "Promela", ProgrammingLanguage),
    Tech("PROSE modeling language", "PROSE modeling language", ProgrammingLanguage),
    Tech("PROTEL", "PROTEL", ProgrammingLanguage),
    Tech("ProvideX", "ProvideX", ProgrammingLanguage),
    Tech("Pro*C", "Pro*C", ProgrammingLanguage),
    Tech("Pure", "Pure", ProgrammingLanguage),
    Tech("Python", "Python", ProgrammingLanguage),
    Tech("Qalb", "Qalb", ProgrammingLanguage),
    Tech("QtScript", "QtScript", ProgrammingLanguage),
    Tech("QuakeC", "QuakeC", ProgrammingLanguage),
    Tech("QPL", "QPL", ProgrammingLanguage),
    Tech("R++", "R++", ProgrammingLanguage),
    Tech("Racket", "Racket", ProgrammingLanguage),
    Tech("RAPID", "RAPID", ProgrammingLanguage),
    Tech("Rapira", "Rapira", ProgrammingLanguage),
    Tech("Ratfiv", "Ratfiv", ProgrammingLanguage),
    Tech("Ratfor", "Ratfor", ProgrammingLanguage),
    Tech("REBOL", "REBOL", ProgrammingLanguage),
    Tech("Redcode", "Redcode", ProgrammingLanguage),
    Tech("REFAL", "REFAL", ProgrammingLanguage),
    Tech("Reia", "Reia", ProgrammingLanguage),
    Tech("Revolution", "Revolution", ProgrammingLanguage),
    Tech("rex", "rex", ProgrammingLanguage),
    Tech("REXX", "REXX", ProgrammingLanguage),
    Tech("Rlab", "Rlab", ProgrammingLanguage),
    Tech("RobotC", "RobotC", ProgrammingLanguage),
    Tech("ROOP", "ROOP", ProgrammingLanguage),
    Tech("RPG", "RPG", ProgrammingLanguage),
    Tech("RPL", "RPL", ProgrammingLanguage),
    Tech("RSL", "RSL", ProgrammingLanguage),
    Tech("RTL/2", "RTL/2", ProgrammingLanguage),
    Tech("Ruby", "Ruby", ProgrammingLanguage),
    Tech("RuneScript", "RuneScript", ProgrammingLanguage),
    Tech("Rust", "Rust", ProgrammingLanguage),
    Tech("S-Lang", "S-Lang", ProgrammingLanguage),
    Tech("S-Plus", "S-PLUS", ProgrammingLanguage),
    Tech("SA-C", "SA-C", ProgrammingLanguage),
    Tech("SabreTalk", "SabreTalk", ProgrammingLanguage),
    Tech("SAIL", "SAIL", ProgrammingLanguage),
    Tech("SALSA", "SALSA", ProgrammingLanguage),
    Tech("SAM76", "SAM76", ProgrammingLanguage),
    Tech("SAS", "SAS", ProgrammingLanguage),
    Tech("SASL", "SASL", ProgrammingLanguage),
    Tech("Sather", "Sather", ProgrammingLanguage),
    Tech("Sawzall", "Sawzall", ProgrammingLanguage),
    Tech("SBL", "SBL", ProgrammingLanguage),
    Tech("Scala", "Scala", ProgrammingLanguage),
    Tech("Scheme", "Scheme", ProgrammingLanguage),
    Tech("Scilab", "Scilab", ProgrammingLanguage),
    Tech("Script.NET", "Script.NET", ProgrammingLanguage),
    Tech("Sed", "Sed", ProgrammingLanguage),
    Tech("Seed7", "Seed7", ProgrammingLanguage),
    Tech("Self", "Self", ProgrammingLanguage),
    Tech("SenseTalk", "SenseTalk", ProgrammingLanguage),
    Tech("SequenceL", "SequenceL", ProgrammingLanguage),
    Tech("SETL", "SETL", ProgrammingLanguage),
    Tech("Shift Script", "Shift Script", ProgrammingLanguage),
    Tech("SIMPOL", "SIMPOL", ProgrammingLanguage),
    Tech("SIGNAL", "SIGNAL", ProgrammingLanguage),
    Tech("SIMSCRIPT", "SIMSCRIPT", ProgrammingLanguage),
    Tech("Simula", "Simula", ProgrammingLanguage),
    Tech("Simulink", "Simulink", ProgrammingLanguage),
    Tech("SISAL", "SISAL", ProgrammingLanguage),
    Tech("SLIP", "SLIP", ProgrammingLanguage),
    Tech("Smalltalk", "Smalltalk", ProgrammingLanguage),
    Tech("Small Basic", "Small Basic", ProgrammingLanguage),
    Tech("SML", "SML", ProgrammingLanguage),
    Tech("Snap!", "Snap!", ProgrammingLanguage),
    Tech("SNOBOL", "SNOBOL", ProgrammingLanguage),
    Tech("SPITBOL", "SPITBOL", ProgrammingLanguage),
    Tech("Snowball", "Snowball", ProgrammingLanguage),
    Tech("SOL", "SOL", ProgrammingLanguage),
    Tech("Span", "Span", ProgrammingLanguage),
    Tech("SPARK", "SPARK", ProgrammingLanguage),
    Tech("Speedcode", "Speedcode", ProgrammingLanguage),
    Tech("SPIN", "SPIN", ProgrammingLanguage),
    Tech("SP/k", "SP/k", ProgrammingLanguage),
    Tech("SPS", "SPS", ProgrammingLanguage),
    Tech("Squeak", "Squeak", ProgrammingLanguage),
    Tech("Squirrel", "Squirrel", ProgrammingLanguage),
    Tech("SR", "SR", ProgrammingLanguage),
    Tech("S/SL", "S/SL", ProgrammingLanguage),
    Tech("Starlogo", "Starlogo", ProgrammingLanguage),
    Tech("Strand", "Strand", ProgrammingLanguage),
    Tech("Stata", "Stata", ProgrammingLanguage),
    Tech("Stateflow", "Stateflow", ProgrammingLanguage),
    Tech("Subtext", "Subtext", ProgrammingLanguage),
    Tech("SuperCollider", "SuperCollider", ProgrammingLanguage),
    Tech("SuperTalk", "SuperTalk", ProgrammingLanguage),
    Tech("Swift", "Swift", ProgrammingLanguage),
    Tech("SYMPL", "SYMPL", ProgrammingLanguage),
    Tech("SyncCharts", "SyncCharts", ProgrammingLanguage),
    Tech("SystemVerilog", "SystemVerilog", ProgrammingLanguage),
    Tech("TACL", "TACL", ProgrammingLanguage),
    Tech("TACPOL", "TACPOL", ProgrammingLanguage),
    Tech("TADS", "TADS", ProgrammingLanguage),
    Tech("TAL", "TAL", ProgrammingLanguage),
    Tech("Tcl", "Tcl", ProgrammingLanguage),
    Tech("Tea", "Tea", ProgrammingLanguage),
    Tech("TECO", "TECO", ProgrammingLanguage),
    Tech("TELCOMP", "TELCOMP", ProgrammingLanguage),
    Tech("TeX", "TeX", ProgrammingLanguage),
    Tech("TEX", "TEX", ProgrammingLanguage),
    Tech("TIE", "TIE", ProgrammingLanguage),
    Tech("Timber", "Timber", ProgrammingLanguage),
    Tech("TMG", "TMG", ProgrammingLanguage),
    Tech("Tom", "Tom", ProgrammingLanguage),
    Tech("TOM", "TOM", ProgrammingLanguage),
    Tech("Topspeed", "Topspeed", ProgrammingLanguage),
    Tech("TPU", "TPU", ProgrammingLanguage),
    Tech("Trac", "Trac", ProgrammingLanguage),
    Tech("TTM", "TTM", ProgrammingLanguage),
    Tech("T-SQL", "T-SQL", ProgrammingLanguage),
    Tech("TTCN", "TTCN", ProgrammingLanguage),
    Tech("Turing", "Turing", ProgrammingLanguage),
    Tech("TUTOR", "TUTOR", ProgrammingLanguage),
    Tech("TXL", "TXL", ProgrammingLanguage),
    Tech("TypeScript", "TypeScript", ProgrammingLanguage),
    Tech("Turbo C++", "Turbo C++", ProgrammingLanguage),
    Tech("Ubercode", "Ubercode", ProgrammingLanguage),
    Tech("UCSD pascal", "UCSD Pascal", ProgrammingLanguage),
    Tech("Umple", "Umple", ProgrammingLanguage),
    Tech("Unicon", "Unicon", ProgrammingLanguage),
    Tech("Uniface", "Uniface", ProgrammingLanguage),
    Tech("UNITY", "UNITY", ProgrammingLanguage),
    Tech("UnrealScript", "UnrealScript", ProgrammingLanguage),
    Tech("Vala", "Vala", ProgrammingLanguage),
    Tech("VBA", "VBA", ProgrammingLanguage),
    Tech("VBScript", "VBScript", ProgrammingLanguage),
    Tech("Verilog", "Verilog", ProgrammingLanguage),
    Tech("VHDL", "VHDL", ProgrammingLanguage),
    Tech("Visual Basic", "Visual Basic", ProgrammingLanguage),
    Tech("Visual Basic .NET", "Visual Basic .NET", ProgrammingLanguage),
    Tech("VB.net", "Visual Basic .NET", ProgrammingLanguage),
    Tech("VB.NET", "Visual Basic .NET", ProgrammingLanguage),
    Tech("Visual Dataflex", "Visual DataFlex", ProgrammingLanguage),
    Tech("Visual DialogScript", "Visual DialogScript", ProgrammingLanguage),
    Tech("Visual Fortran", "Visual Fortran", ProgrammingLanguage),
    Tech("Visual FoxPro", "Visual FoxPro", ProgrammingLanguage),
    Tech("Visual J++", "Visual J++", ProgrammingLanguage),
    Tech("Visual j#", "Visual J#", ProgrammingLanguage),
    Tech("Visual Objects", "Visual Objects", ProgrammingLanguage),
    Tech("Visual Prolog", "Visual Prolog", ProgrammingLanguage),
    Tech("VSXu", "VSXu", ProgrammingLanguage),
    Tech("Vvvv", "Vvvv", ProgrammingLanguage),
    Tech("WATFIV", "WATFIV", ProgrammingLanguage),
    Tech("WATFOR", "WATFOR", ProgrammingLanguage),
    Tech("WebDNA", "WebDNA", ProgrammingLanguage),
    Tech("WebQL", "WebQL", ProgrammingLanguage),
    Tech("Windows Powershell", "Windows PowerShell", ProgrammingLanguage),
    Tech("Winbatch", "Winbatch", ProgrammingLanguage),
    Tech("Wolfram", "Wolfram", ProgrammingLanguage),
    Tech("Wyvern", "Wyvern", ProgrammingLanguage),
    Tech("X++", "X++", ProgrammingLanguage),
    Tech("X#", "X#", ProgrammingLanguage),
    Tech("X10", "X10", ProgrammingLanguage),
    Tech("XBL", "XBL", ProgrammingLanguage),
    Tech("XC", "XC", ProgrammingLanguage),
    Tech("XMOS architecture", "XMOS architecture", ProgrammingLanguage),
    Tech("xHarbour", "xHarbour", ProgrammingLanguage),
    Tech("XL", "XL", ProgrammingLanguage),
    Tech("Xojo", "Xojo", ProgrammingLanguage),
    Tech("XOTcl", "XOTcl", ProgrammingLanguage),
    Tech("XPL", "XPL", ProgrammingLanguage),
    Tech("XPL0", "XPL0", ProgrammingLanguage),
    Tech("XQuery", "XQuery", ProgrammingLanguage),
    Tech("XSB", "XSB", ProgrammingLanguage),
    Tech("XSLT", "XSLT", ProgrammingLanguage),
    Tech("Xtend", "Xtend", ProgrammingLanguage),
    Tech("Yorick", "Yorick", ProgrammingLanguage),
    Tech("YQL", "YQL", ProgrammingLanguage),
    Tech("Z Notation", "Z notation", ProgrammingLanguage),
    Tech("Zeno", "Zeno", ProgrammingLanguage),
    Tech("ZOPL", "ZOPL", ProgrammingLanguage),
    Tech("ZPL", "ZPL", ProgrammingLanguage),
    Tech("Flutter", "Flutter", ProgrammingLanguage),
    Tech("HTML5", "HTML", ProgrammingLanguage),
    Tech("HTML", "HTML", ProgrammingLanguage),
    Tech("CSS", "CSS", ProgrammingLanguage),
    Tech("Outsystems", "OutSystems", ProgrammingLanguage),
    Tech("OutSystems", "OutSystems", ProgrammingLanguage),
    // ################# Front-End Stuff #################
    Tech("Sass", "Sass", Other),
    Tech("SCSS", "Sass", Other),
    // ################# Platforms #################
    Tech("Node.js", "Node.js", Platform),
    Tech("node.js", "Node.js", Platform),
    Tech("Node", "Node.js", Platform),
    Tech("NodeJS", "Node.js", Platform),
    Tech("Nodejs", "Node.js", Platform),
    Tech("NodeJs", "Node.js", Platform),
    Tech(".NET", ".NET", Platform),
    Tech(".net", ".NET", Platform),
    Tech(".Net", ".NET", Platform),
    // ################# Infrastructure #################
    Tech("Terraform", "Terraform", InfrastructureTool),
    Tech("Kubernetes", "Kubernetes", InfrastructureTool),
    Tech("Docker", "Docker", InfrastructureTool),
    Tech("Vagrant", "Vagrant", InfrastructureTool),
    Tech("Helm", "Helm", InfrastructureTool),
    Tech("MicroK8s", "MicroK8s", InfrastructureTool),
    Tech("Microk8s", "MicroK8s", InfrastructureTool),
    Tech("Chef", "Chef", InfrastructureTool),
    Tech("Puppet", "Puppet", InfrastructureTool),
    Tech("Ansible", "Ansible", InfrastructureTool),
    // ################# Mobile #################
    Tech("iOS", "iOS", Mobile),
    Tech("Android", "Android", Mobile),
    Tech("Cordova", "Cordova", Mobile),
    Tech("React Native", "React Native", Mobile),
    Tech("Xamarin", "Xamarin", Mobile),
    Tech("Ionic", "Ionic", Mobile),
    // ################# Frameworks #################
    Tech("Ruby", "Ruby On Rails", Framework),
    Tech("Ruby On Rails", "Ruby On Rails", Framework),
    Tech("Play", "Play Framework", Framework),
    Tech("Play Framework", "Play Framework", Framework),
    Tech("ASP.NET", "ASP.NET", Framework),
    Tech("Electron", "Electron", Framework),
    // ## Java
    Tech("Spring", "Spring Framework", Framework),
    Tech("Spring Boot", "Spring Framework", Framework),
    Tech("Springboot", "Spring Framework", Framework),
    Tech("Spring Framework", "Spring Framework", Framework),
    Tech("Apache Jena", "Apache Jena", Framework),
    Tech("Jena", "Apache Jena", Framework),
    Tech("Apache Wicket", "Apache Wicket", Framework),
    Tech("Wicket", "Apache Wicket", Framework),
    Tech("Vert.x", "Vert.x", Framework),
    Tech("Dropwizard", "Dropwizard", Framework),
    // ## Python
    Tech("Twisted", "Twisted", Framework),
    Tech("Pyramid", "Pyramid", Framework),
    Tech("Flask", "Flask", Framework),
    Tech("Django", "Django", Framework),
    Tech("FastAPI", "FastAPI", Framework),
    // ## PHP
    Tech("CakePHP", "CakePHP", Framework),
    Tech("Symfony", "Symfony", Framework),
    Tech("Laravel", "Laravel", Framework),
    Tech("Lumen", "Lumen", Framework),
    Tech("Phalcon", "Phalcon", Framework),
    // ## Javascript
    Tech("Ember", "Ember.js", Framework),
    Tech("Ember.js", "Ember.js", Framework),
    Tech("Meteor", "Meteor", Framework),
    Tech("Vue.js", "Vue.js", Framework),
    Tech("Marionette.js", "Marionette.js", Framework),
    Tech("Angular", "Angular", Framework),
    Tech("Angular.js", "Angular", Framework),
    Tech("KnockoutJS", "Knockout", Framework),
    Tech("Knockout.js", "Knockout", Framework),
    Tech("Knockout", "Knockout", Framework),
    Tech("React", "React", Framework),
    Tech("react.js", "React", Framework),
    Tech("React.js", "React", Framework),
    Tech("Cycle.js", "Cycle.js", Framework),
    Tech("Draft.js", "Draft.js", Framework),
    Tech("Next.js", "Next.js", Framework),
    Tech("Aurelia", "Aurelia", Framework),
    Tech("choo", "choo", Framework),
    Tech("Preact", "Preact", Framework),
    Tech("Hyperapp", "Hyperapp", Framework),
    Tech("Blazor", "Blazor", Framework),
    Tech("Yew", "Yew", Framework),
    Tech("Svelte", "Svelte", Framework),
    // ## CSS
    Tech("Boostrap", "Boostrap", Framework),
    Tech("Materialize", "Materialize", Framework),
    Tech("materializecss", "Materialize", Framework),
    Tech("MaterializeCSS", "Materialize", Framework),
    Tech("normalize.css", "normalize.css", Framework),
    Tech("sanitize.css", "sanitize.css", Framework),
    Tech("minireset.css", "minireset.css", Framework),
    Tech("inuitcss", "inuitcss", Framework),
    Tech("modern-css-reset", "modern-css-reset", Framework),
    Tech("ress", "ress", Framework),
    Tech("modern-normalize", "modern-normalize", Framework),
    Tech("Water.css", "Water.css", Framework),
    Tech("sakura", "sakura", Framework),
    Tech("Marx", "Marx", Framework),
    Tech("Tacit", "Tacit", Framework),
    Tech("awsm.css", "awsm.css", Framework),
    Tech("Pure", "Pure", Framework),
    Tech("Milligram", "Milligram", Framework),
    Tech("Picnic CSS", "Picnic CSS", Framework),
    Tech("Wing", "Wing", Framework),
    Tech("Chota", "Chota", Framework),
    Tech("Semantic UI", "Semantic UI", Framework),
    Tech("Bulma", "Bulma", Framework),
    Tech("Foundation", "Foundation", Framework),
    Tech("UIkit", "UIkit", Framework),
    Tech("Spectre.css", "Spectre.css", Framework),
    Tech("Tachyons", "Tachyons", Framework),
    Tech("Primer", "Primer", Framework),
    Tech("Carbon Components", "Carbon Components", Framework),
    Tech("Blaze UI", "Blaze UI", Framework),
    Tech("PatternFly", "PatternFly", Framework),
    Tech("turretcss", "turretcss", Framework),
    Tech("Cirrus", "Cirrus", Framework),
    Tech("HiQ", "HiQ", Framework),
    Tech("Material Components Web", "Material Components Web", Framework),
    Tech("MUI", "MUI", Framework),
    Tech("Propeller", "Propeller", Framework),
    Tech("Tailwind CSS", "Tailwind CSS", Framework),
    Tech("NES.css", "NES.css", Framework),
    Tech("98.css", "98.css", Framework),
    Tech("Gutenberg", "Gutenberg", Framework),
    Tech("Tufte CSS", "Tufte CSS", Framework),
    Tech("Bojler", "Bojler", Framework),
    Tech("Bourbon", "Bourbon", Framework),
    // ################# Libraries #################
    // ## Javascript
    Tech("Backbone", "Backbone.js", Library),
    Tech("Backbone.js", "Backbone.js", Library),
    Tech("Polymer", "Polymer", Library),
    Tech("Relay", "Relay", Library),
    Tech("D3", "D3", Library),
    Tech("jQuery", "jQuery", Library),
    Tech("lit-html", "lit-html", Library),
    Tech("WebGL", "WebGL", Library),
    Tech("Redux", "Redux", Library),
    // ## Scala
    Tech("Cats", "Cats", Library),
    Tech("Doobie", "Doobie", Library),
    Tech("fs2", "fs2", Library),
    Tech("Akka", "Akka", Library),
    Tech("akka", "Akka", Library),
    // ################# Big Data #################
    Tech("Hadoop", "Hadoop", Other),
    Tech("Spark", "Apache Spark", Other),
    Tech("Apache Spark", "Apache Spark", Other),
    Tech("Qlik", "Qlik", Other),
    Tech("Splunk", "Splunk", Other),
    // ################# Databases #################
    Tech("MySQL", "MySQL", Database),
    Tech("mySQL", "MySQL", Database),
    Tech("SQLAlchemy", "SQLAlchemy", Database),
    Tech("InfluxDB", "InfluxDB", Database),
    Tech("Neo4j", "Neo4j", Database),
    Tech("MongoDB", "MongoDB", Database),
    Tech("RethinkDB", "RethinkDB", Database),
    Tech("TinkerPop", "TinkerPop", Database),
    Tech("PostgreSQL", "PostgreSQL", Database),
    Tech("CouchDB", "CouchDB", Database),
    Tech("HBase", "HBase", Database),
    Tech("Contexture", "Contexture", Database),
    Tech("SQL Server", "SQL Server", Database),
    Tech("MSSQL", "SQL Server", Database),
    Tech("mssql", "SQL Server", Database),
    Tech("DynamoDB", "DynamoDB", Database),
    Tech("Redis", "Redis", Database),
    Tech("redis", "Redis", Database),
    Tech("Couchbase", "Couchbase", Database),
    Tech("Cassandra", "Apache Cassandra", Database),
    Tech("HBase", "Apache HBase", Database),
    Tech("Neo4j", "Neo4j", Database),
    Tech("Oracle Database", "Oracle Database", Database),
    Tech("Oracle database", "Oracle Database", Database),
    // ################# Build Tools #################
    Tech("Maven", "Maven", BuildTool),
    Tech("Gradle", "Gradle", BuildTool),
    Tech("CMake", "CMake", BuildTool),
    Tech("sbt", "sbt", BuildTool),
    // ################# Test/QA #################
    Tech("Cucumber", "Cucumber", TestAndQA),
    Tech("Selenium", "Selenium", TestAndQA),
    Tech("Test Rail", "TestRail", TestAndQA),
    Tech("TestRail", "TestRail", TestAndQA),
    Tech("BackstopJS", "BackstopJS", TestAndQA),
    Tech("JUnit", "JUnit", TestAndQA),
    Tech("PHPUnit", "PHPUnit", TestAndQA),
    Tech("Sikuli", "Sikuli", TestAndQA),
    Tech("TestLink", "TestLink", TestAndQA),
    Tech("Testlink", "TestLink", TestAndQA),
    Tech("JMeter", "JMeter", TestAndQA),
    Tech("Cypress", "Cypress", TestAndQA),
    Tech("TestCafe", "TestCafe", TestAndQA),
    Tech("SonarQube", "SonarQube", TestAndQA),
    Tech("Protractor", "Protractor", TestAndQA),
    Tech("Jasmine", "Jasmine", TestAndQA),
    // ################# CI/CD #################
    Tech("Abstruse CI", "Abstruse CI", CICD),
    Tech("Agola", "Agola", CICD),
    Tech("Appcircle.io", "Appcircle.io", CICD),
    Tech("Appveyor", "Appveyor", CICD),
    Tech("Assertible", "Assertible", CICD),
    Tech("AWS CodeBuild", "AWS CodeBuild", CICD),
    Tech("Azure DevOps", "Azure DevOps", CICD),
    Tech("Badwolf", "Badwolf", CICD),
    Tech("Bamboo", "Bamboo", CICD),
    Tech("BitBucket Pipelines", "BitBucket Pipelines", CICD),
    Tech("Bitrise", "Bitrise", CICD),
    Tech("Buddy", "Buddy", CICD),
    Tech("builds.sr.ht", "builds.sr.ht", CICD),
    Tech("Buildkite", "Buildkite", CICD),
    Tech("Chrono CI", "Chrono CI", CICD),
    Tech("Circle CI", "CircleCI", CICD),
    Tech("CircleCI", "CircleCI", CICD),
    Tech("Cirrus CI", "Cirrus CI", CICD),
    Tech("Codacy", "Codacy", CICD),
    Tech("Code Climate", "Code Climate", CICD),
    Tech("CodeFresh", "CodeFresh", CICD),
    Tech("Codemagic", "Codemagic", CICD),
    Tech("Codeship", "Codeship", CICD),
    Tech("Concourse CI", "Concourse CI", CICD),
    Tech("continuousphp", "continuousphp", CICD),
    Tech("Coveralls", "Coveralls", CICD),
    Tech("Coverity", "Coverity", CICD),
    Tech("Drone", "Drone", CICD),
    Tech("Ebert", "Ebert", CICD),
    Tech("Evergreen", "Evergreen", CICD),
    Tech("flow.ci", "flow.ci", CICD),
    Tech("GoCD", "GoCD", CICD),
    Tech("GitLab", "GitLab", CICD),
    Tech("GitGud", "GitGud", CICD),
    Tech("GitHub Actions", "GitHub Actions", CICD),
    Tech("Hound CI", "Hound CI", CICD),
    Tech("Hydra", "Hydra", CICD),
    Tech("Jenkins", "Jenkins", CICD),
    Tech("Kritika", "Kritika", CICD),
    Tech("minci", "minci", CICD),
    Tech("Peakflow", "Peakflow", CICD),
    Tech("Previs", "Previs", CICD),
    Tech("Probo.CI", "Probo.CI", CICD),
    Tech("RazorOps", "RazorOps", CICD),
    Tech("Saucelabs", "Saucelabs", CICD),
    Tech("Scrutinizer", "Scrutinizer", CICD),
    Tech("Semaphore", "Semaphore", CICD),
    Tech("Shippable", "Shippable", CICD),
    Tech("Sider", "Sider", CICD),
    Tech("Snake CI", "Snake CI", CICD),
    Tech("StyleCI", "StyleCI", CICD),
    Tech("TeamCity", "TeamCity", CICD),
    Tech("Travis CI", "Travis CI", CICD),
    Tech("Wercker", "Wercker", CICD),
    Tech("Zuul", "Zuul", CICD),
    // ################# Cloud #################
    Tech("Amazon Web Services", "AWS", Cloud),
    Tech("AWS", "AWS", Cloud),
    Tech("Azure", "Azure", Cloud),
    Tech("IBM Cloud", "IBM Cloud", Cloud),
    Tech("Digital Ocean", "Digital Ocean", Cloud),
    Tech("Heroku", "Heroku", Cloud),
    // ################# Query Languages #################
    Tech("XPath", "XPath", QueryLanguage),
    // ################# Tools #################
    Tech("Postman", "Postman", Tool),
    Tech("DbVisualizer", "DbVisualizer", Tool),
    Tech("Hibernate", "Hibernate", Tool),
    Tech("Google Web Toolkit", "Google Web Toolkit", Tool),
    Tech("GWT", "Google Web Toolkit", Tool),
    Tech("PostCSS", "PostCSS", Tool),
    Tech("webpack", "webpack", Tool),
    Tech("Browserify", "Browserify", Tool),
    Tech("Prometheus", "Prometheus", Tool),
    Tech("Thanos", "Thanos", Tool),
    Tech("Loki", "Loki", Tool),
    Tech("Elasticserch", "Elasticserch", Tool),
    Tech("Kibana", "Kibana", Tool),
    Tech("Graylog", "Graylog", Tool),
    Tech("ReportPortal", "ReportPortal", Tool),
    Tech("Git", "Git", Tool),
    Tech("Kafka", "Kafka", Tool),
    Tech("Chartio", "Chartio", Tool),
    Tech("LaunchDarkly", "LaunchDarkly", Tool),
    Tech("Tomcat", "Apache Tomcat", Tool),
    Tech("DBeaver", "DBeaver", Tool),
    Tech("ActiveMQ", "ActiveMQ", Tool),
    Tech("AMQ", "ActiveMQ", Tool),
    Tech("SteamBase", "TIBCO StreamBase", Tool),
    Tech("Steambase", "TIBCO StreamBase", Tool),
    Tech("Grafana", "Grafana", Tool),
  )
}
