package com.lcampos.duration_per_tech

case class Tech(
  name: String,
  canonName: String,
  category: TechCategory
)

sealed trait TechCategory {
  val uiRepresentation: String
}
case object ProgrammingLanguage extends TechCategory {
  val uiRepresentation: String = "Programming Languages"
}
case object Database extends TechCategory {
  val uiRepresentation: String = "Databases"
}
case object CICD extends TechCategory {
  val uiRepresentation: String = "CI/CD"
}
case object TestAndQA extends TechCategory {
  val uiRepresentation: String = "Test and QA"
}
case object BuildTool extends TechCategory {
  val uiRepresentation: String = "Build Tools"
}

case object Framework extends TechCategory {
  val uiRepresentation: String = "Frameworks"
}

case object Cloud extends TechCategory {
  val uiRepresentation: String = "Cloud"
}

case object Mobile extends TechCategory {
  val uiRepresentation: String = "Mobile"
}

case object Other extends TechCategory {
  val uiRepresentation: String = "Other"
}

object TechList {

  /**
   * Sources:
   * - https://github.com/sindresorhus/awesome
   */

  val all: List[Tech] = List(
    // ################# Programming languages #################
    Tech("a#", "A#", ProgrammingLanguage),
    Tech(".net", ".NET", ProgrammingLanguage),
    Tech("a# (axiom)", "A# (Axiom)", ProgrammingLanguage),
    Tech("a-0 system", "A-0 System", ProgrammingLanguage),
    Tech("a+", "A+", ProgrammingLanguage),
    Tech("a++", "A++", ProgrammingLanguage),
    Tech("abap", "ABAP", ProgrammingLanguage),
    Tech("abc", "ABC", ProgrammingLanguage),
    Tech("abc algol", "ABC ALGOL", ProgrammingLanguage),
    Tech("able", "ABLE", ProgrammingLanguage),
    Tech("abset", "ABSET", ProgrammingLanguage),
    Tech("absys", "ABSYS", ProgrammingLanguage),
    Tech("acc", "ACC", ProgrammingLanguage),
    Tech("accent", "Accent", ProgrammingLanguage),
    Tech("ace dasl", "Ace DASL", ProgrammingLanguage),
    Tech("acl2", "ACL2", ProgrammingLanguage),
    Tech("act-iii", "ACT-III", ProgrammingLanguage),
    Tech("action!", "Action!", ProgrammingLanguage),
    Tech("actionscript", "ActionScript", ProgrammingLanguage),
    Tech("ada", "Ada", ProgrammingLanguage),
    Tech("adenine", "Adenine", ProgrammingLanguage),
    Tech("agda", "Agda", ProgrammingLanguage),
    Tech("agilent vee", "Agilent VEE", ProgrammingLanguage),
    Tech("agora", "Agora", ProgrammingLanguage),
    Tech("aimms", "AIMMS", ProgrammingLanguage),
    Tech("alef", "Alef", ProgrammingLanguage),
    Tech("alf", "ALF", ProgrammingLanguage),
    Tech("algol 58", "ALGOL 58", ProgrammingLanguage),
    Tech("algol 60", "ALGOL 60", ProgrammingLanguage),
    Tech("algol 68", "ALGOL 68", ProgrammingLanguage),
    Tech("algol w", "ALGOL W", ProgrammingLanguage),
    Tech("alice", "Alice", ProgrammingLanguage),
    Tech("alma-0", "Alma-0", ProgrammingLanguage),
    Tech("ambienttalk", "AmbientTalk", ProgrammingLanguage),
    Tech("amiga e", "Amiga E", ProgrammingLanguage),
    Tech("amos", "AMOS", ProgrammingLanguage),
    Tech("ampl", "AMPL", ProgrammingLanguage),
    Tech("apl", "APL", ProgrammingLanguage),
    Tech("applescript", "AppleScript", ProgrammingLanguage),
    Tech("arc", "Arc", ProgrammingLanguage),
    Tech("arexx", "ARexx", ProgrammingLanguage),
    Tech("argus", "Argus", ProgrammingLanguage),
    Tech("aspectj", "AspectJ", ProgrammingLanguage),
    Tech("assembly language", "Assembly language", ProgrammingLanguage),
    Tech("ats", "ATS", ProgrammingLanguage),
    Tech("ateji px", "Ateji PX", ProgrammingLanguage),
    Tech("autohotkey", "AutoHotkey", ProgrammingLanguage),
    Tech("autocoder", "Autocoder", ProgrammingLanguage),
    Tech("autoit", "AutoIt", ProgrammingLanguage),
    Tech("autolisp / visual lisp", "AutoLISP / Visual LISP", ProgrammingLanguage),
    Tech("averest", "Averest", ProgrammingLanguage),
    Tech("awk", "AWK", ProgrammingLanguage),
    Tech("axum", "Axum", ProgrammingLanguage),
    Tech("b", "B", ProgrammingLanguage),
    Tech("babbage", "Babbage", ProgrammingLanguage),
    Tech("bash", "Bash", ProgrammingLanguage),
    Tech("basic", "BASIC", ProgrammingLanguage),
    Tech("bc", "bc", ProgrammingLanguage),
    Tech("bcpl", "BCPL", ProgrammingLanguage),
    Tech("beanshell", "BeanShell", ProgrammingLanguage),
    Tech("batch (windows/dos)", "Batch (Windows/Dos)", ProgrammingLanguage),
    Tech("bertrand", "Bertrand", ProgrammingLanguage),
    Tech("beta", "BETA", ProgrammingLanguage),
    Tech("bigwig", "Bigwig", ProgrammingLanguage),
    Tech("bistro", "Bistro", ProgrammingLanguage),
    Tech("bitc", "BitC", ProgrammingLanguage),
    Tech("bliss", "BLISS", ProgrammingLanguage),
    Tech("blue", "Blue", ProgrammingLanguage),
    Tech("bon", "Bon", ProgrammingLanguage),
    Tech("boo", "Boo", ProgrammingLanguage),
    Tech("boomerang", "Boomerang", ProgrammingLanguage),
    Tech("bourne shell", "Bourne shell", ProgrammingLanguage),
    Tech("bash", "bash", ProgrammingLanguage),
    Tech("ksh", "ksh", ProgrammingLanguage),
    Tech("brew", "BREW", ProgrammingLanguage),
    Tech("bpel", "BPEL", ProgrammingLanguage),
    Tech("c", "C", ProgrammingLanguage),
    Tech("c--", "C--", ProgrammingLanguage),
    Tech("c++", "C++", ProgrammingLanguage),
    Tech("c#", "C#", ProgrammingLanguage),
    Tech("c/al", "C/AL", ProgrammingLanguage),
    Tech("caché objectscript", "Caché ObjectScript", ProgrammingLanguage),
    Tech("c shell", "C Shell", ProgrammingLanguage),
    Tech("caml", "Caml", ProgrammingLanguage),
    Tech("candle", "Candle", ProgrammingLanguage),
    Tech("cayenne", "Cayenne", ProgrammingLanguage),
    Tech("cduce", "CDuce", ProgrammingLanguage),
    Tech("cecil", "Cecil", ProgrammingLanguage),
    Tech("cel", "Cel", ProgrammingLanguage),
    Tech("cesil", "Cesil", ProgrammingLanguage),
    Tech("ceylon", "Ceylon", ProgrammingLanguage),
    Tech("cfengine", "CFEngine", ProgrammingLanguage),
    Tech("cfml", "CFML", ProgrammingLanguage),
    Tech("cg", "Cg", ProgrammingLanguage),
    Tech("ch", "Ch", ProgrammingLanguage),
    Tech("chapel", "Chapel", ProgrammingLanguage),
    Tech("chain", "CHAIN", ProgrammingLanguage),
    Tech("charity", "Charity", ProgrammingLanguage),
    Tech("charm", "Charm", ProgrammingLanguage),
    Tech("chef", "Chef", ProgrammingLanguage),
    Tech("chill", "CHILL", ProgrammingLanguage),
    Tech("chip-8", "CHIP-8", ProgrammingLanguage),
    Tech("chomski", "chomski", ProgrammingLanguage),
    Tech("chuck", "ChucK", ProgrammingLanguage),
    Tech("cics", "CICS", ProgrammingLanguage),
    Tech("cilk", "Cilk", ProgrammingLanguage),
    Tech("cl", "CL", ProgrammingLanguage),
    Tech("claire", "Claire", ProgrammingLanguage),
    Tech("clarion", "Clarion", ProgrammingLanguage),
    Tech("clean", "Clean", ProgrammingLanguage),
    Tech("clipper", "Clipper", ProgrammingLanguage),
    Tech("clist", "CLIST", ProgrammingLanguage),
    Tech("clojure", "Clojure", ProgrammingLanguage),
    Tech("clu", "CLU", ProgrammingLanguage),
    Tech("cms-2", "CMS-2", ProgrammingLanguage),
    Tech("cobol", "COBOL", ProgrammingLanguage),
    Tech("cobra", "Cobra", ProgrammingLanguage),
    Tech("coffeescript", "CoffeeScript", ProgrammingLanguage),
    Tech("cola", "Cola", ProgrammingLanguage),
    Tech("coldc", "ColdC", ProgrammingLanguage),
    Tech("coldfusion", "ColdFusion", ProgrammingLanguage),
    Tech("comal", "COMAL", ProgrammingLanguage),
    Tech("comit", "COMIT", ProgrammingLanguage),
    Tech("common lisp", "Common Lisp", ProgrammingLanguage),
    Tech("compass", "COMPASS", ProgrammingLanguage),
    Tech("component pascal", "Component Pascal", ProgrammingLanguage),
    Tech("converge", "Converge", ProgrammingLanguage),
    Tech("coq", "Coq", ProgrammingLanguage),
    Tech("coral 66", "Coral 66", ProgrammingLanguage),
    Tech("corn", "Corn", ProgrammingLanguage),
    Tech("corvision", "CorVision", ProgrammingLanguage),
    Tech("cowsel", "COWSEL", ProgrammingLanguage),
    Tech("cpl", "CPL", ProgrammingLanguage),
    Tech("csh", "csh", ProgrammingLanguage),
    Tech("csp", "CSP", ProgrammingLanguage),
    Tech("csound", "Csound", ProgrammingLanguage),
    Tech("cuda", "CUDA", ProgrammingLanguage),
    Tech("curl", "Curl", ProgrammingLanguage),
    Tech("curry", "Curry", ProgrammingLanguage),
    Tech("cyclone", "Cyclone", ProgrammingLanguage),
    Tech("cython", "Cython", ProgrammingLanguage),
    Tech("d", "D", ProgrammingLanguage),
    Tech("dasl", "DASL", ProgrammingLanguage),
    Tech("dasl", "DASL", ProgrammingLanguage),
    Tech("dart", "Dart", ProgrammingLanguage),
    Tech("dataflex", "DataFlex", ProgrammingLanguage),
    Tech("datalog", "Datalog", ProgrammingLanguage),
    Tech("datatrieve", "DATATRIEVE", ProgrammingLanguage),
    Tech("dbase", "dBase", ProgrammingLanguage),
    Tech("dc", "dc", ProgrammingLanguage),
    Tech("dcl", "DCL", ProgrammingLanguage),
    Tech("deesel", "Deesel", ProgrammingLanguage),
    Tech("delphi", "Delphi", ProgrammingLanguage),
    Tech("dinkc", "DinkC", ProgrammingLanguage),
    Tech("dibol", "DIBOL", ProgrammingLanguage),
    Tech("dog", "Dog", ProgrammingLanguage),
    Tech("draco", "Draco", ProgrammingLanguage),
    Tech("drakon", "DRAKON", ProgrammingLanguage),
    Tech("dylan", "Dylan", ProgrammingLanguage),
    Tech("dynamo", "DYNAMO", ProgrammingLanguage),
    Tech("e", "E", ProgrammingLanguage),
    Tech("e#", "E#", ProgrammingLanguage),
    Tech("ease", "Ease", ProgrammingLanguage),
    Tech("easy pl/i", "Easy PL/I", ProgrammingLanguage),
    Tech("easy programming language", "Easy Programming Language", ProgrammingLanguage),
    Tech("easytrieve plus", "EASYTRIEVE PLUS", ProgrammingLanguage),
    Tech("ecmascript", "ECMAScript", ProgrammingLanguage),
    Tech("edinburgh imp", "Edinburgh IMP", ProgrammingLanguage),
    Tech("egl", "EGL", ProgrammingLanguage),
    Tech("eiffel", "Eiffel", ProgrammingLanguage),
    Tech("elan", "ELAN", ProgrammingLanguage),
    Tech("elixir", "Elixir", ProgrammingLanguage),
    Tech("elm", "Elm", ProgrammingLanguage),
    Tech("emacs lisp", "Emacs Lisp", ProgrammingLanguage),
    Tech("emerald", "Emerald", ProgrammingLanguage),
    Tech("epigram", "Epigram", ProgrammingLanguage),
    Tech("epl", "EPL", ProgrammingLanguage),
    Tech("erlang", "Erlang", ProgrammingLanguage),
    Tech("es", "es", ProgrammingLanguage),
    Tech("escapade", "Escapade", ProgrammingLanguage),
    Tech("escher", "Escher", ProgrammingLanguage),
    Tech("espol", "ESPOL", ProgrammingLanguage),
    Tech("esterel", "Esterel", ProgrammingLanguage),
    Tech("etoys", "Etoys", ProgrammingLanguage),
    Tech("euclid", "Euclid", ProgrammingLanguage),
    Tech("euler", "Euler", ProgrammingLanguage),
    Tech("euphoria", "Euphoria", ProgrammingLanguage),
    Tech("euslisp robot programming language", "EusLisp Robot Programming Language", ProgrammingLanguage),
    Tech("cms exec", "CMS EXEC", ProgrammingLanguage),
    Tech("exec 2", "EXEC 2", ProgrammingLanguage),
    Tech("executable uml", "Executable UML", ProgrammingLanguage),
    Tech("f", "F", ProgrammingLanguage),
    Tech("f#", "F#", ProgrammingLanguage),
    Tech("factor", "Factor", ProgrammingLanguage),
    Tech("falcon", "Falcon", ProgrammingLanguage),
    Tech("fancy", "Fancy", ProgrammingLanguage),
    Tech("fantom", "Fantom", ProgrammingLanguage),
    Tech("faust", "FAUST", ProgrammingLanguage),
    Tech("felix", "Felix", ProgrammingLanguage),
    Tech("ferite", "Ferite", ProgrammingLanguage),
    Tech("ffp", "FFP", ProgrammingLanguage),
    Tech("fjölnir", "Fjölnir", ProgrammingLanguage),
    Tech("fl", "FL", ProgrammingLanguage),
    Tech("flavors", "Flavors", ProgrammingLanguage),
    Tech("flex", "Flex", ProgrammingLanguage),
    Tech("flow-matic", "FLOW-MATIC", ProgrammingLanguage),
    Tech("focal", "FOCAL", ProgrammingLanguage),
    Tech("focus", "FOCUS", ProgrammingLanguage),
    Tech("foil", "FOIL", ProgrammingLanguage),
    Tech("formac", "FORMAC", ProgrammingLanguage),
    Tech("@formula", "@Formula", ProgrammingLanguage),
    Tech("forth", "Forth", ProgrammingLanguage),
    Tech("fortran", "Fortran", ProgrammingLanguage),
    Tech("fortress", "Fortress", ProgrammingLanguage),
    Tech("foxbase", "FoxBase", ProgrammingLanguage),
    Tech("foxpro", "FoxPro", ProgrammingLanguage),
    Tech("fp", "FP", ProgrammingLanguage),
    Tech("fpr", "FPr", ProgrammingLanguage),
    Tech("franz lisp", "Franz Lisp", ProgrammingLanguage),
    Tech("frege", "Frege", ProgrammingLanguage),
    Tech("f-script", "F-Script", ProgrammingLanguage),
    Tech("fsprog", "FSProg", ProgrammingLanguage),
    Tech("g", "G", ProgrammingLanguage),
    Tech("google apps script", "Google Apps Script", ProgrammingLanguage),
    Tech("game maker language", "Game Maker Language", ProgrammingLanguage),
    Tech("gamemonkey script", "GameMonkey Script", ProgrammingLanguage),
    Tech("gams", "GAMS", ProgrammingLanguage),
    Tech("g-code", "G-code", ProgrammingLanguage),
    Tech("genie", "Genie", ProgrammingLanguage),
    Tech("gdl", "GDL", ProgrammingLanguage),
    Tech("gibiane", "Gibiane", ProgrammingLanguage),
    Tech("gj", "GJ", ProgrammingLanguage),
    Tech("george", "GEORGE", ProgrammingLanguage),
    Tech("glsl", "GLSL", ProgrammingLanguage),
    Tech("gnu e", "GNU E", ProgrammingLanguage),
    Tech("gm", "GM", ProgrammingLanguage),
    Tech("go", "Go", ProgrammingLanguage),
    Tech("go!", "Go!", ProgrammingLanguage),
    Tech("gödel", "Gödel", ProgrammingLanguage),
    Tech("godiva", "Godiva", ProgrammingLanguage),
    Tech("gom (good old mad)", "GOM (Good Old Mad)", ProgrammingLanguage),
    Tech("goo", "Goo", ProgrammingLanguage),
    Tech("gosu", "Gosu", ProgrammingLanguage),
    Tech("gotran", "GOTRAN", ProgrammingLanguage),
    Tech("gpss", "GPSS", ProgrammingLanguage),
    Tech("graphtalk", "GraphTalk", ProgrammingLanguage),
    Tech("grass", "GRASS", ProgrammingLanguage),
    Tech("groovy", "Groovy", ProgrammingLanguage),
    Tech("hack (programming language)", "Hack (programming language)", ProgrammingLanguage),
    Tech("hal/s", "HAL/S", ProgrammingLanguage),
    Tech("hamilton c shell", "Hamilton C shell", ProgrammingLanguage),
    Tech("harbour", "Harbour", ProgrammingLanguage),
    Tech("hartmann pipelines", "Hartmann pipelines", ProgrammingLanguage),
    Tech("haskell", "Haskell", ProgrammingLanguage),
    Tech("haxe", "Haxe", ProgrammingLanguage),
    Tech("high level assembly", "High Level Assembly", ProgrammingLanguage),
    Tech("hlsl", "HLSL", ProgrammingLanguage),
    Tech("hop", "Hop", ProgrammingLanguage),
    Tech("hope", "Hope", ProgrammingLanguage),
    Tech("hugo", "Hugo", ProgrammingLanguage),
    Tech("hume", "Hume", ProgrammingLanguage),
    Tech("hypertalk", "HyperTalk", ProgrammingLanguage),
    Tech("ibm basic assembly language", "IBM Basic assembly language", ProgrammingLanguage),
    Tech("ibm hascript", "IBM HAScript", ProgrammingLanguage),
    Tech("ibm informix-4gl", "IBM Informix-4GL", ProgrammingLanguage),
    Tech("ibm rpg", "IBM RPG", ProgrammingLanguage),
    Tech("ici", "ICI", ProgrammingLanguage),
    Tech("icon", "Icon", ProgrammingLanguage),
    Tech("idl", "IDL", ProgrammingLanguage),
    Tech("idris", "Idris", ProgrammingLanguage),
    Tech("imp", "IMP", ProgrammingLanguage),
    Tech("inform", "Inform", ProgrammingLanguage),
    Tech("io", "Io", ProgrammingLanguage),
    Tech("ioke", "Ioke", ProgrammingLanguage),
    Tech("ipl", "IPL", ProgrammingLanguage),
    Tech("iptscrae", "IPTSCRAE", ProgrammingLanguage),
    Tech("islisp", "ISLISP", ProgrammingLanguage),
    Tech("ispf", "ISPF", ProgrammingLanguage),
    Tech("iswim", "ISWIM", ProgrammingLanguage),
    Tech("j", "J", ProgrammingLanguage),
    Tech("j#", "J#", ProgrammingLanguage),
    Tech("j++", "J++", ProgrammingLanguage),
    Tech("jade", "JADE", ProgrammingLanguage),
    Tech("jako", "Jako", ProgrammingLanguage),
    Tech("jal", "JAL", ProgrammingLanguage),
    Tech("janus", "Janus", ProgrammingLanguage),
    Tech("jass", "JASS", ProgrammingLanguage),
    Tech("java", "Java", ProgrammingLanguage),
    Tech("javascript", "JavaScript", ProgrammingLanguage),
    Tech("jcl", "JCL", ProgrammingLanguage),
    Tech("jean", "JEAN", ProgrammingLanguage),
    Tech("join java", "Join Java", ProgrammingLanguage),
    Tech("joss", "JOSS", ProgrammingLanguage),
    Tech("joule", "Joule", ProgrammingLanguage),
    Tech("jovial", "JOVIAL", ProgrammingLanguage),
    Tech("joy", "Joy", ProgrammingLanguage),
    Tech("jscript", "JScript", ProgrammingLanguage),
    Tech("jscript .net", "JScript .NET", ProgrammingLanguage),
    Tech("javafx script", "JavaFX Script", ProgrammingLanguage),
    Tech("julia", "Julia", ProgrammingLanguage),
    Tech("jython", "Jython", ProgrammingLanguage),
    Tech("k", "K", ProgrammingLanguage),
    Tech("kaleidoscope", "Kaleidoscope", ProgrammingLanguage),
    Tech("karel", "Karel", ProgrammingLanguage),
    Tech("karel++", "Karel++", ProgrammingLanguage),
    Tech("kee", "KEE", ProgrammingLanguage),
    Tech("kixtart", "Kixtart", ProgrammingLanguage),
    Tech("kif", "KIF", ProgrammingLanguage),
    Tech("kojo", "Kojo", ProgrammingLanguage),
    Tech("kotlin", "Kotlin", ProgrammingLanguage),
    Tech("krc", "KRC", ProgrammingLanguage),
    Tech("krl", "KRL", ProgrammingLanguage),
    Tech("kuka", "KUKA", ProgrammingLanguage),
    Tech("krypton", "KRYPTON", ProgrammingLanguage),
    Tech("ksh", "ksh", ProgrammingLanguage),
    Tech("l", "L", ProgrammingLanguage),
    Tech("l# .net", "L# .NET", ProgrammingLanguage),
    Tech("labview", "LabVIEW", ProgrammingLanguage),
    Tech("ladder", "Ladder", ProgrammingLanguage),
    Tech("lagoona", "Lagoona", ProgrammingLanguage),
    Tech("lansa", "LANSA", ProgrammingLanguage),
    Tech("lasso", "Lasso", ProgrammingLanguage),
    Tech("latex", "LaTeX", ProgrammingLanguage),
    Tech("lava", "Lava", ProgrammingLanguage),
    Tech("lc-3", "LC-3", ProgrammingLanguage),
    Tech("leda", "Leda", ProgrammingLanguage),
    Tech("legoscript", "Legoscript", ProgrammingLanguage),
    Tech("lil", "LIL", ProgrammingLanguage),
    Tech("lilypond", "LilyPond", ProgrammingLanguage),
    Tech("limbo", "Limbo", ProgrammingLanguage),
    Tech("limnor", "Limnor", ProgrammingLanguage),
    Tech("linc", "LINC", ProgrammingLanguage),
    Tech("lingo", "Lingo", ProgrammingLanguage),
    Tech("linoleum", "Linoleum", ProgrammingLanguage),
    Tech("lis", "LIS", ProgrammingLanguage),
    Tech("lisa", "LISA", ProgrammingLanguage),
    Tech("lisaac", "Lisaac", ProgrammingLanguage),
    Tech("lisp", "Lisp", ProgrammingLanguage),
    Tech("lite-c", "Lite-C", ProgrammingLanguage),
    Tech("lithe", "Lithe", ProgrammingLanguage),
    Tech("little b", "Little b", ProgrammingLanguage),
    Tech("logo", "Logo", ProgrammingLanguage),
    Tech("logtalk", "Logtalk", ProgrammingLanguage),
    Tech("lpc", "LPC", ProgrammingLanguage),
    Tech("lse", "LSE", ProgrammingLanguage),
    Tech("lsl", "LSL", ProgrammingLanguage),
    Tech("livecode", "LiveCode", ProgrammingLanguage),
    Tech("livescript", "LiveScript", ProgrammingLanguage),
    Tech("lua", "Lua", ProgrammingLanguage),
    Tech("lucid", "Lucid", ProgrammingLanguage),
    Tech("lustre", "Lustre", ProgrammingLanguage),
    Tech("lyapas", "LYaPAS", ProgrammingLanguage),
    Tech("lynx", "Lynx", ProgrammingLanguage),
    Tech("m2001", "M2001", ProgrammingLanguage),
    Tech("m4", "M4", ProgrammingLanguage),
    Tech("machine code", "Machine code", ProgrammingLanguage),
    Tech("mad/i", "MAD/I", ProgrammingLanguage),
    Tech("magik", "Magik", ProgrammingLanguage),
    Tech("magma", "Magma", ProgrammingLanguage),
    Tech("maple", "Maple", ProgrammingLanguage),
    Tech("mapper", "MAPPER", ProgrammingLanguage),
    Tech("mark-iv", "MARK-IV", ProgrammingLanguage),
    Tech("mary", "Mary", ProgrammingLanguage),
    Tech("masm microsoft assembly x86", "MASM Microsoft Assembly x86", ProgrammingLanguage),
    Tech("mathematica", "Mathematica", ProgrammingLanguage),
    Tech("matlab", "MATLAB", ProgrammingLanguage),
    Tech("maxima", "Maxima", ProgrammingLanguage),
    Tech("macsyma", "Macsyma", ProgrammingLanguage),
    Tech("max", "Max", ProgrammingLanguage),
    Tech("maxscript", "MaxScript", ProgrammingLanguage),
    Tech("maya (mel)", "Maya (MEL)", ProgrammingLanguage),
    Tech("mdl", "MDL", ProgrammingLanguage),
    Tech("mercury", "Mercury", ProgrammingLanguage),
    Tech("mesa", "Mesa", ProgrammingLanguage),
    Tech("metacard", "Metacard", ProgrammingLanguage),
    Tech("metafont", "Metafont", ProgrammingLanguage),
    Tech("metal", "MetaL", ProgrammingLanguage),
    Tech("microcode", "Microcode", ProgrammingLanguage),
    Tech("microscript", "MicroScript", ProgrammingLanguage),
    Tech("miis", "MIIS", ProgrammingLanguage),
    Tech("millscript", "MillScript", ProgrammingLanguage),
    Tech("mimic", "MIMIC", ProgrammingLanguage),
    Tech("mirah", "Mirah", ProgrammingLanguage),
    Tech("miranda", "Miranda", ProgrammingLanguage),
    Tech("miva script", "MIVA Script", ProgrammingLanguage),
    Tech("ml", "ML", ProgrammingLanguage),
    Tech("moby", "Moby", ProgrammingLanguage),
    Tech("model 204", "Model 204", ProgrammingLanguage),
    Tech("modelica", "Modelica", ProgrammingLanguage),
    Tech("modula", "Modula", ProgrammingLanguage),
    Tech("modula-2", "Modula-2", ProgrammingLanguage),
    Tech("modula-3", "Modula-3", ProgrammingLanguage),
    Tech("mohol", "Mohol", ProgrammingLanguage),
    Tech("moo", "MOO", ProgrammingLanguage),
    Tech("mortran", "Mortran", ProgrammingLanguage),
    Tech("mouse", "Mouse", ProgrammingLanguage),
    Tech("mpd", "MPD", ProgrammingLanguage),
    Tech("cil", "CIL", ProgrammingLanguage),
    Tech("msl", "MSL", ProgrammingLanguage),
    Tech("mumps", "MUMPS", ProgrammingLanguage),
    Tech("nasm", "NASM", ProgrammingLanguage),
    Tech("natural", "NATURAL", ProgrammingLanguage),
    Tech("napier88", "Napier88", ProgrammingLanguage),
    Tech("neko", "Neko", ProgrammingLanguage),
    Tech("nemerle", "Nemerle", ProgrammingLanguage),
    Tech("nesc", "nesC", ProgrammingLanguage),
    Tech("nesl", "NESL", ProgrammingLanguage),
    Tech("net.data", "Net.Data", ProgrammingLanguage),
    Tech("netlogo", "NetLogo", ProgrammingLanguage),
    Tech("netrexx", "NetRexx", ProgrammingLanguage),
    Tech("newlisp", "NewLISP", ProgrammingLanguage),
    Tech("newp", "NEWP", ProgrammingLanguage),
    Tech("newspeak", "Newspeak", ProgrammingLanguage),
    Tech("newtonscript", "NewtonScript", ProgrammingLanguage),
    Tech("ngl", "NGL", ProgrammingLanguage),
    Tech("nial", "Nial", ProgrammingLanguage),
    Tech("nice", "Nice", ProgrammingLanguage),
    Tech("nickle", "Nickle", ProgrammingLanguage),
    Tech("nim", "Nim", ProgrammingLanguage),
    Tech("npl", "NPL", ProgrammingLanguage),
    Tech("not exactly c", "Not eXactly C", ProgrammingLanguage),
    Tech("not quite c", "Not Quite C", ProgrammingLanguage),
    Tech("nsis", "NSIS", ProgrammingLanguage),
    Tech("nu", "Nu", ProgrammingLanguage),
    Tech("nwscript", "NWScript", ProgrammingLanguage),
    Tech("nxt-g", "NXT-G", ProgrammingLanguage),
    Tech("o:xml", "o:XML", ProgrammingLanguage),
    Tech("oak", "Oak", ProgrammingLanguage),
    Tech("oberon", "Oberon", ProgrammingLanguage),
    Tech("obix", "Obix", ProgrammingLanguage),
    Tech("obj2", "OBJ2", ProgrammingLanguage),
    Tech("object lisp", "Object Lisp", ProgrammingLanguage),
    Tech("objectlogo", "ObjectLOGO", ProgrammingLanguage),
    Tech("object rexx", "Object REXX", ProgrammingLanguage),
    Tech("object pascal", "Object Pascal", ProgrammingLanguage),
    Tech("objective-c", "Objective-C", ProgrammingLanguage),
    Tech("objective-j", "Objective-J", ProgrammingLanguage),
    Tech("obliq", "Obliq", ProgrammingLanguage),
    Tech("obol", "Obol", ProgrammingLanguage),
    Tech("ocaml", "OCaml", ProgrammingLanguage),
    Tech("occam", "occam", ProgrammingLanguage),
    Tech("occam-π", "occam-π", ProgrammingLanguage),
    Tech("octave", "Octave", ProgrammingLanguage),
    Tech("omnimark", "OmniMark", ProgrammingLanguage),
    Tech("onyx", "Onyx", ProgrammingLanguage),
    Tech("opa", "Opa", ProgrammingLanguage),
    Tech("opal", "Opal", ProgrammingLanguage),
    Tech("opencl", "OpenCL", ProgrammingLanguage),
    Tech("openedge abl", "OpenEdge ABL", ProgrammingLanguage),
    Tech("opl", "OPL", ProgrammingLanguage),
    Tech("ops5", "OPS5", ProgrammingLanguage),
    Tech("optimj", "OptimJ", ProgrammingLanguage),
    Tech("orc", "Orc", ProgrammingLanguage),
    Tech("orca/modula-2", "ORCA/Modula-2", ProgrammingLanguage),
    Tech("oriel", "Oriel", ProgrammingLanguage),
    Tech("orwell", "Orwell", ProgrammingLanguage),
    Tech("oxygene", "Oxygene", ProgrammingLanguage),
    Tech("oz", "Oz", ProgrammingLanguage),
    Tech("p#", "P#", ProgrammingLanguage),
    Tech("parasail (programming language)", "ParaSail (programming language)", ProgrammingLanguage),
    Tech("pari/gp", "PARI/GP", ProgrammingLanguage),
    Tech("pascal", "Pascal", ProgrammingLanguage),
    Tech("pawn", "Pawn", ProgrammingLanguage),
    Tech("pcastl", "PCASTL", ProgrammingLanguage),
    Tech("pcf", "PCF", ProgrammingLanguage),
    Tech("pearl", "PEARL", ProgrammingLanguage),
    Tech("peoplecode", "PeopleCode", ProgrammingLanguage),
    Tech("perl", "Perl", ProgrammingLanguage),
    Tech("pdl", "PDL", ProgrammingLanguage),
    Tech("php", "PHP", ProgrammingLanguage),
    Tech("phrogram", "Phrogram", ProgrammingLanguage),
    Tech("pico", "Pico", ProgrammingLanguage),
    Tech("picolisp", "Picolisp", ProgrammingLanguage),
    Tech("pict", "Pict", ProgrammingLanguage),
    Tech("pike", "Pike", ProgrammingLanguage),
    Tech("pikt", "PIKT", ProgrammingLanguage),
    Tech("pilot", "PILOT", ProgrammingLanguage),
    Tech("pipelines", "Pipelines", ProgrammingLanguage),
    Tech("pizza", "Pizza", ProgrammingLanguage),
    Tech("pl-11", "PL-11", ProgrammingLanguage),
    Tech("pl/0", "PL/0", ProgrammingLanguage),
    Tech("pl/b", "PL/B", ProgrammingLanguage),
    Tech("pl/c", "PL/C", ProgrammingLanguage),
    Tech("pl/i", "PL/I", ProgrammingLanguage),
    Tech("pl/m", "PL/M", ProgrammingLanguage),
    Tech("pl/p", "PL/P", ProgrammingLanguage),
    Tech("pl/sql", "PL/SQL", ProgrammingLanguage),
    Tech("pl360", "PL360", ProgrammingLanguage),
    Tech("planc", "PLANC", ProgrammingLanguage),
    Tech("plankalkül", "Plankalkül", ProgrammingLanguage),
    Tech("planner", "Planner", ProgrammingLanguage),
    Tech("plex", "PLEX", ProgrammingLanguage),
    Tech("plexil", "PLEXIL", ProgrammingLanguage),
    Tech("plus", "Plus", ProgrammingLanguage),
    Tech("pop-11", "POP-11", ProgrammingLanguage),
    Tech("postscript", "PostScript", ProgrammingLanguage),
    Tech("portable", "PortablE", ProgrammingLanguage),
    Tech("powerhouse", "Powerhouse", ProgrammingLanguage),
    Tech("powerbuilder", "PowerBuilder", ProgrammingLanguage),
    Tech("powershell", "PowerShell", ProgrammingLanguage),
    Tech("ppl", "PPL", ProgrammingLanguage),
    Tech("processing", "Processing", ProgrammingLanguage),
    Tech("processing.js", "Processing.js", ProgrammingLanguage),
    Tech("prograph", "Prograph", ProgrammingLanguage),
    Tech("proiv", "PROIV", ProgrammingLanguage),
    Tech("prolog", "Prolog", ProgrammingLanguage),
    Tech("promal", "PROMAL", ProgrammingLanguage),
    Tech("promela", "Promela", ProgrammingLanguage),
    Tech("prose modeling language", "PROSE modeling language", ProgrammingLanguage),
    Tech("protel", "PROTEL", ProgrammingLanguage),
    Tech("providex", "ProvideX", ProgrammingLanguage),
    Tech("pro*c", "Pro*C", ProgrammingLanguage),
    Tech("pure", "Pure", ProgrammingLanguage),
    Tech("python", "Python", ProgrammingLanguage),
    Tech("q (equational programming language)", "Q (equational programming language)", ProgrammingLanguage),
    Tech("q (programming language from kx systems)", "Q (programming language from Kx Systems)", ProgrammingLanguage),
    Tech("qalb", "Qalb", ProgrammingLanguage),
    Tech("qtscript", "QtScript", ProgrammingLanguage),
    Tech("quakec", "QuakeC", ProgrammingLanguage),
    Tech("qpl", "QPL", ProgrammingLanguage),
    Tech("r", "R", ProgrammingLanguage),
    Tech("r++", "R++", ProgrammingLanguage),
    Tech("racket", "Racket", ProgrammingLanguage),
    Tech("rapid", "RAPID", ProgrammingLanguage),
    Tech("rapira", "Rapira", ProgrammingLanguage),
    Tech("ratfiv", "Ratfiv", ProgrammingLanguage),
    Tech("ratfor", "Ratfor", ProgrammingLanguage),
    Tech("rc", "rc", ProgrammingLanguage),
    Tech("rebol", "REBOL", ProgrammingLanguage),
    Tech("red", "Red", ProgrammingLanguage),
    Tech("redcode", "Redcode", ProgrammingLanguage),
    Tech("refal", "REFAL", ProgrammingLanguage),
    Tech("reia", "Reia", ProgrammingLanguage),
    Tech("revolution", "Revolution", ProgrammingLanguage),
    Tech("rex", "rex", ProgrammingLanguage),
    Tech("rexx", "REXX", ProgrammingLanguage),
    Tech("rlab", "Rlab", ProgrammingLanguage),
    Tech("robotc", "RobotC", ProgrammingLanguage),
    Tech("roop", "ROOP", ProgrammingLanguage),
    Tech("rpg", "RPG", ProgrammingLanguage),
    Tech("rpl", "RPL", ProgrammingLanguage),
    Tech("rsl", "RSL", ProgrammingLanguage),
    Tech("rtl/2", "RTL/2", ProgrammingLanguage),
    Tech("ruby", "Ruby", ProgrammingLanguage),
    Tech("runescript", "RuneScript", ProgrammingLanguage),
    Tech("rust", "Rust", ProgrammingLanguage),
    Tech("s", "S", ProgrammingLanguage),
    Tech("s2", "S2", ProgrammingLanguage),
    Tech("s3", "S3", ProgrammingLanguage),
    Tech("s-lang", "S-Lang", ProgrammingLanguage),
    Tech("s-plus", "S-PLUS", ProgrammingLanguage),
    Tech("sa-c", "SA-C", ProgrammingLanguage),
    Tech("sabretalk", "SabreTalk", ProgrammingLanguage),
    Tech("sail", "SAIL", ProgrammingLanguage),
    Tech("salsa", "SALSA", ProgrammingLanguage),
    Tech("sam76", "SAM76", ProgrammingLanguage),
    Tech("sas", "SAS", ProgrammingLanguage),
    Tech("sasl", "SASL", ProgrammingLanguage),
    Tech("sather", "Sather", ProgrammingLanguage),
    Tech("sawzall", "Sawzall", ProgrammingLanguage),
    Tech("sbl", "SBL", ProgrammingLanguage),
    Tech("scala", "Scala", ProgrammingLanguage),
    Tech("scheme", "Scheme", ProgrammingLanguage),
    Tech("scilab", "Scilab", ProgrammingLanguage),
    Tech("scratch", "Scratch", ProgrammingLanguage),
    Tech("script.net", "Script.NET", ProgrammingLanguage),
    Tech("sed", "Sed", ProgrammingLanguage),
    Tech("seed7", "Seed7", ProgrammingLanguage),
    Tech("self", "Self", ProgrammingLanguage),
    Tech("sensetalk", "SenseTalk", ProgrammingLanguage),
    Tech("sequencel", "SequenceL", ProgrammingLanguage),
    Tech("setl", "SETL", ProgrammingLanguage),
    Tech("shift script", "Shift Script", ProgrammingLanguage),
    Tech("simpol", "SIMPOL", ProgrammingLanguage),
    Tech("signal", "SIGNAL", ProgrammingLanguage),
    Tech("simple", "SiMPLE", ProgrammingLanguage),
    Tech("simscript", "SIMSCRIPT", ProgrammingLanguage),
    Tech("simula", "Simula", ProgrammingLanguage),
    Tech("simulink", "Simulink", ProgrammingLanguage),
    Tech("sisal", "SISAL", ProgrammingLanguage),
    Tech("slip", "SLIP", ProgrammingLanguage),
    Tech("small", "SMALL", ProgrammingLanguage),
    Tech("smalltalk", "Smalltalk", ProgrammingLanguage),
    Tech("small basic", "Small Basic", ProgrammingLanguage),
    Tech("sml", "SML", ProgrammingLanguage),
    Tech("snap!", "Snap!", ProgrammingLanguage),
    Tech("snobol", "SNOBOL", ProgrammingLanguage),
    Tech("spitbol", "SPITBOL", ProgrammingLanguage),
    Tech("snowball", "Snowball", ProgrammingLanguage),
    Tech("sol", "SOL", ProgrammingLanguage),
    Tech("span", "Span", ProgrammingLanguage),
    Tech("spark", "SPARK", ProgrammingLanguage),
    Tech("speedcode", "Speedcode", ProgrammingLanguage),
    Tech("spin", "SPIN", ProgrammingLanguage),
    Tech("sp/k", "SP/k", ProgrammingLanguage),
    Tech("sps", "SPS", ProgrammingLanguage),
    Tech("squeak", "Squeak", ProgrammingLanguage),
    Tech("squirrel", "Squirrel", ProgrammingLanguage),
    Tech("sr", "SR", ProgrammingLanguage),
    Tech("s/sl", "S/SL", ProgrammingLanguage),
    Tech("stackless python", "Stackless Python", ProgrammingLanguage),
    Tech("starlogo", "Starlogo", ProgrammingLanguage),
    Tech("strand", "Strand", ProgrammingLanguage),
    Tech("stata", "Stata", ProgrammingLanguage),
    Tech("stateflow", "Stateflow", ProgrammingLanguage),
    Tech("subtext", "Subtext", ProgrammingLanguage),
    Tech("supercollider", "SuperCollider", ProgrammingLanguage),
    Tech("supertalk", "SuperTalk", ProgrammingLanguage),
    Tech("swift", "Swift", ProgrammingLanguage),
    Tech("sympl", "SYMPL", ProgrammingLanguage),
    Tech("synccharts", "SyncCharts", ProgrammingLanguage),
    Tech("systemverilog", "SystemVerilog", ProgrammingLanguage),
    Tech("t", "T", ProgrammingLanguage),
    Tech("tacl", "TACL", ProgrammingLanguage),
    Tech("tacpol", "TACPOL", ProgrammingLanguage),
    Tech("tads", "TADS", ProgrammingLanguage),
    Tech("tal", "TAL", ProgrammingLanguage),
    Tech("tcl", "Tcl", ProgrammingLanguage),
    Tech("tea", "Tea", ProgrammingLanguage),
    Tech("teco", "TECO", ProgrammingLanguage),
    Tech("telcomp", "TELCOMP", ProgrammingLanguage),
    Tech("tex", "TeX", ProgrammingLanguage),
    Tech("tex", "TEX", ProgrammingLanguage),
    Tech("tie", "TIE", ProgrammingLanguage),
    Tech("timber", "Timber", ProgrammingLanguage),
    Tech("tmg", "TMG", ProgrammingLanguage),
    Tech("tom", "Tom", ProgrammingLanguage),
    Tech("tom", "TOM", ProgrammingLanguage),
    Tech("topspeed", "Topspeed", ProgrammingLanguage),
    Tech("tpu", "TPU", ProgrammingLanguage),
    Tech("trac", "Trac", ProgrammingLanguage),
    Tech("ttm", "TTM", ProgrammingLanguage),
    Tech("t-sql", "T-SQL", ProgrammingLanguage),
    Tech("ttcn", "TTCN", ProgrammingLanguage),
    Tech("turing", "Turing", ProgrammingLanguage),
    Tech("tutor", "TUTOR", ProgrammingLanguage),
    Tech("txl", "TXL", ProgrammingLanguage),
    Tech("typescript", "TypeScript", ProgrammingLanguage),
    Tech("turbo c++", "Turbo C++", ProgrammingLanguage),
    Tech("ubercode", "Ubercode", ProgrammingLanguage),
    Tech("ucsd pascal", "UCSD Pascal", ProgrammingLanguage),
    Tech("umple", "Umple", ProgrammingLanguage),
    Tech("unicon", "Unicon", ProgrammingLanguage),
    Tech("uniface", "Uniface", ProgrammingLanguage),
    Tech("unity", "UNITY", ProgrammingLanguage),
    Tech("unix shell", "Unix shell", ProgrammingLanguage),
    Tech("unrealscript", "UnrealScript", ProgrammingLanguage),
    Tech("vala", "Vala", ProgrammingLanguage),
    Tech("vba", "VBA", ProgrammingLanguage),
    Tech("vbscript", "VBScript", ProgrammingLanguage),
    Tech("verilog", "Verilog", ProgrammingLanguage),
    Tech("vhdl", "VHDL", ProgrammingLanguage),
    Tech("visual basic", "Visual Basic", ProgrammingLanguage),
    Tech("visual basic .net", "Visual Basic .NET", ProgrammingLanguage),
    Tech("visual dataflex", "Visual DataFlex", ProgrammingLanguage),
    Tech("visual dialogscript", "Visual DialogScript", ProgrammingLanguage),
    Tech("visual fortran", "Visual Fortran", ProgrammingLanguage),
    Tech("visual foxpro", "Visual FoxPro", ProgrammingLanguage),
    Tech("visual j++", "Visual J++", ProgrammingLanguage),
    Tech("visual j#", "Visual J#", ProgrammingLanguage),
    Tech("visual objects", "Visual Objects", ProgrammingLanguage),
    Tech("visual prolog", "Visual Prolog", ProgrammingLanguage),
    Tech("vsxu", "VSXu", ProgrammingLanguage),
    Tech("vvvv", "Vvvv", ProgrammingLanguage),
    Tech("watfiv", "WATFIV", ProgrammingLanguage),
    Tech("watfor", "WATFOR", ProgrammingLanguage),
    Tech("webdna", "WebDNA", ProgrammingLanguage),
    Tech("webql", "WebQL", ProgrammingLanguage),
    Tech("windows powershell", "Windows PowerShell", ProgrammingLanguage),
    Tech("winbatch", "Winbatch", ProgrammingLanguage),
    Tech("wolfram", "Wolfram", ProgrammingLanguage),
    Tech("wyvern", "Wyvern", ProgrammingLanguage),
    Tech("x++", "X++", ProgrammingLanguage),
    Tech("x#", "X#", ProgrammingLanguage),
    Tech("x10", "X10", ProgrammingLanguage),
    Tech("xbl", "XBL", ProgrammingLanguage),
    Tech("xc", "XC", ProgrammingLanguage),
    Tech("xmos architecture", "XMOS architecture", ProgrammingLanguage),
    Tech("xharbour", "xHarbour", ProgrammingLanguage),
    Tech("xl", "XL", ProgrammingLanguage),
    Tech("xojo", "Xojo", ProgrammingLanguage),
    Tech("xotcl", "XOTcl", ProgrammingLanguage),
    Tech("xpl", "XPL", ProgrammingLanguage),
    Tech("xpl0", "XPL0", ProgrammingLanguage),
    Tech("xquery", "XQuery", ProgrammingLanguage),
    Tech("xsb", "XSB", ProgrammingLanguage),
    Tech("xslt", "XSLT", ProgrammingLanguage),
    Tech("xpath", "XPath", ProgrammingLanguage),
    Tech("xtend", "Xtend", ProgrammingLanguage),
    Tech("yorick", "Yorick", ProgrammingLanguage),
    Tech("yql", "YQL", ProgrammingLanguage),
    Tech("z notation", "Z notation", ProgrammingLanguage),
    Tech("zeno", "Zeno", ProgrammingLanguage),
    Tech("zopl", "ZOPL", ProgrammingLanguage),
    Tech("zpl", "ZPL", ProgrammingLanguage),
    Tech("node.js", "Node.js", ProgrammingLanguage),
    Tech("flutter", "Flutter", ProgrammingLanguage),
    Tech("html", "HTML", ProgrammingLanguage),
    Tech("html5", "HTML", ProgrammingLanguage),
    Tech("css", "CSS", ProgrammingLanguage),
    // ################# Platforms #################
    Tech("electron", "Electron", Other),
    Tech("cordova", "Cordova", Other),
    Tech("react native", "React Native", Other),
    Tech("xamarin", "Xamarin", Other),
    Tech("linux", "Linux", Other),
    Tech("containers", "Containers", Other),
    Tech("ebpf", "eBPF", Other),
    Tech("arch-based projects", "Arch-based Projects", Other),
    Tech("macos", "macOS", Other),
    Tech("command-line", "Command-Line", Other),
    Tech("screensavers", "Screensavers", Other),
    Tech("apps", "Apps", Other),
    Tech("open source apps", "Open Source Apps", Other),
    Tech("watchos", "watchOS", Other),
    Tech("jvm", "JVM", Other),
    Tech("salesforce", "Salesforce", Other),
    Tech("windows", "Windows", Other),
    Tech("ipfs", "IPFS", Other),
    Tech("fuse", "Fuse", Other),
    Tech("heroku", "Heroku", Other),
    Tech("raspberry pi", "Raspberry Pi", Other),
    Tech("qt", "Qt", Other),
    Tech("webextensions", "WebExtensions", Other),
    Tech("rubymotion", "RubyMotion", Other),
    Tech("smart tv", "Smart TV", Other),
    Tech("gnome", "GNOME", Other),
    Tech("kde", "KDE", Other),
    Tech(".net", ".NET", Other),
    Tech("core", "Core", Other),
    Tech("roslyn", "Roslyn", Other),
    Tech("amazon alexa", "Amazon Alexa", Other),
    Tech("digitalocean", "DigitalOcean", Other),
    Tech("home assistant", "Home Assistant", Other),
    Tech("ibm cloud", "IBM Cloud", Other),
    Tech("firebase", "Firebase", Other),
    Tech("robot operating system 2.0", "Robot Operating System 2.0", Other),
    Tech("adafruit io", "Adafruit IO", Other),
    Tech("cloudflare", "Cloudflare", Other),
    Tech("actions on google", "Actions on Google", Other),
    Tech("esp", "ESP", Other),
    Tech("deno", "Deno", Other),
    Tech("dos", "DOS", Other),
    // ################# Front-End Stuff #################
    Tech("es6 tools", "ES6 Tools", Other),
    Tech("web performance optimization", "Web Performance Optimization", Other),
    Tech("web tools", "Web Tools", Other),
    Tech("critical-path tools", "Critical-Path Tools", Other),
    Tech("scalability", "Scalability", Other),
    Tech("must-watch talks", "Must-Watch Talks", Other),
    Tech("protips", "Protips", Other),
    Tech("react", "React", Other),
    Tech("relay", "Relay", Other),
    Tech("react hooks", "React Hooks", Other),
    Tech("web components", "Web Components", Other),
    Tech("polymer", "Polymer", Other),
    Tech("angular", "Angular", Other),
    Tech("backbone", "Backbone", Other),
    Tech("svg", "SVG", Other),
    Tech("canvas", "Canvas", Other),
    Tech("knockoutjs", "KnockoutJS", Other),
    Tech("dojo toolkit", "Dojo Toolkit", Other),
    Tech("inspiration", "Inspiration", Other),
    Tech("ember", "Ember", Other),
    Tech("android ui", "Android UI", Other),
    Tech("ios ui", "iOS UI", Other),
    Tech("meteor", "Meteor", Other),
    Tech("bem", "BEM", Other),
    Tech("flexbox", "Flexbox", Other),
    Tech("web typography", "Web Typography", Other),
    Tech("web accessibility", "Web Accessibility", Other),
    Tech("material design", "Material Design", Other),
    Tech("d3", "D3", Other),
    Tech("emails", "Emails", Other),
    Tech("jquery", "jQuery", Other),
    Tech("tips", "Tips", Other),
    Tech("web audio", "Web Audio", Other),
    Tech("offline-first", "Offline-First", Other),
    Tech("static website services", "Static Website Services", Other),
    Tech("cycle.js", "Cycle.js", Other),
    Tech("text editing", "Text Editing", Other),
    Tech("motion ui design", "Motion UI Design", Other),
    Tech("vue.js", "Vue.js", Other),
    Tech("marionette.js", "Marionette.js", Other),
    Tech("aurelia", "Aurelia", Other),
    Tech("charting", "Charting", Other),
    Tech("ionic framework 2", "Ionic Framework 2", Other),
    Tech("chrome devtools", "Chrome DevTools", Other),
    Tech("postcss", "PostCSS", Other),
    Tech("draft.js", "Draft.js", Other),
    Tech("service workers", "Service Workers", Other),
    Tech("progressive web apps", "Progressive Web Apps", Other),
    Tech("choo", "choo", Other),
    Tech("redux", "Redux", Other),
    Tech("webpack", "webpack", Other),
    Tech("browserify", "Browserify", Other),
    Tech("sass", "Sass", Other),
    Tech("ant design", "Ant Design", Other),
    Tech("webgl", "WebGL", Other),
    Tech("preact", "Preact", Other),
    Tech("progressive enhancement", "Progressive Enhancement", Other),
    Tech("next.js", "Next.js", Other),
    Tech("hyperapp", "Hyperapp", Other),
    Tech("lit-html", "lit-html", Other),
    Tech("jamstack", "JAMstack", Other),
    Tech("wordpress-gatsby", "WordPress-Gatsby", Other),
    Tech("mobile web development", "Mobile Web Development", Other),
    Tech("storybook", "Storybook", Other),
    Tech("blazor", "Blazor", Other),
    Tech("pagespeed metrics", "PageSpeed Metrics", Other),
    Tech("tailwind css", "Tailwind CSS", Other),
    Tech("seed", "Seed", Other),
    Tech("web performance budget", "Web Performance Budget", Other),
    Tech("web animation", "Web Animation", Other),
    Tech("yew", "Yew", Other),
    Tech("material-ui", "Material-UI", Other),
    Tech("svelte", "Svelte", Other),
    Tech("design systems", "Design systems", Other),
    // ################# Back-End Stuff #################
    Tech("docker", "Docker", Other),
    Tech("vagrant", "Vagrant", Other),
    Tech("pyramid", "Pyramid", Other),
    Tech("play1 framework", "Play1 Framework", Other),
    Tech("cakephp", "CakePHP", Other),
    Tech("symfony", "Symfony", Other),
    Tech("laravel", "Laravel", Other),
    Tech("tall stack", "TALL Stack", Other),
    Tech("gems", "Gems", Other),
    Tech("phalcon", "Phalcon", Other),
    Tech("useful .htaccess snippets", "Useful .htaccess Snippets", Other),
    Tech("nginx", "nginx", Other),
    Tech("dropwizard", "Dropwizard", Other),
    Tech("kubernetes", "Kubernetes", Other),
    Tech("lumen", "Lumen", Other),
    Tech("serverless framework", "Serverless Framework", Other),
    Tech("apache wicket", "Apache Wicket", Other),
    Tech("vert.x", "Vert.x", Other),
    Tech("terraform", "Terraform", Other),
    Tech("vapor", "Vapor", Other),
    Tech("dash", "Dash", Other),
    Tech("fastapi", "FastAPI", Other),
    Tech("cdk", "CDK", Other),
    Tech("git", "Git", Other),
    Tech("kafka", "Kafka", Other),
    // ################# Frameworks #################
    Tech("ios", "iOS", Mobile),
    Tech("android", "Android", Mobile),
    // ################# Frameworks #################
    Tech("spring", "Spring Framework", Framework),
    Tech("springboot", "Spring Framework", Framework),
    Tech("spring framework", "Spring Framework", Framework),
    Tech("flask", "Flask", Framework),
    Tech("rails", "Ruby On Rails", Framework),
    Tech("ruby on rails", "Ruby On Rails", Framework),
    // ################# Big Data #################
    Tech("hadoop", "Hadoop", Other),
    Tech("data engineering", "Data Engineering", Other),
    Tech("streaming", "Streaming", Other),
    Tech("apache spark", "Apache Spark", Other),
    Tech("qlik", "Qlik", Other),
    Tech("splunk", "Splunk", Other),
    // ################# Databases #################
    Tech("mysql", "MySQL", Database),
    Tech("sqlalchemy", "SQLAlchemy", Database),
    Tech("influxdb", "InfluxDB", Database),
    Tech("neo4j", "Neo4j", Database),
    Tech("mongodb", "MongoDB", Database),
    Tech("rethinkdb", "RethinkDB", Database),
    Tech("tinkerpop", "TinkerPop", Database),
    Tech("postgresql", "PostgreSQL", Database),
    Tech("couchdb", "CouchDB", Database),
    Tech("hbase", "HBase", Database),
    Tech("contexture", "Contexture", Database),
    Tech("sql server", "SQL Server", Database),
    Tech("dbvisualizer", "DbVisualizer", Database),
    // ################# Build Tools #################
    Tech("maven", "Maven", BuildTool),
    // ################# Test/QA #################
    Tech("cucumber", "Cucumber", TestAndQA),
    Tech("selenium", "Selenium", TestAndQA),
    Tech("test rail", "TestRail", TestAndQA),
    Tech("testrail", "TestRail", TestAndQA),
    // ################# CI/CD #################
    Tech("jenkins", "Jenkins", CICD),
    // ################# Cloud #################
    Tech("amazon web services", "AWS", Cloud),
    Tech("aws", "AWS", Cloud),
    Tech("azure", "Azure", Cloud),
  )}
